stacks-sbtc/sbtc

Cargo.lock, Cargo.toml, signer/Cargo.toml, signer/src/lib.rs, signer/src/message.rs
closes #104 
This PR introduces the base message type according to the signer communication LLD, and paves the way for future work on the signer message variants and network.
=> feat: Signer message type definition

Cargo.lock, blocklist-client/Cargo.toml, blocklist-client/README.md, blocklist-client/settings.toml, blocklist-client/src/api/routes.rs, blocklist-client/src/config.rs, blocklist-client/src/config/default.toml, blocklist-client/src/main.rs
resolves #121 
Using a static read-only config that gets instantiated via a default config file and environment variables for an improved way to handle config management.
=> Use environment variables for config management

emily/cdk/bin/emily.ts, emily/cdk/lib/constants.ts, emily/cdk/lib/emily-stack.ts, emily/cdk/package.json, emily/cdk/test/emily-stack-util.test.ts, emily/cdk/test/emily-stack.test.ts
The Emily CDK uses a zipped lambda file for the AWS lambda, but if this file isn't present during compile time the cdk template will fail to build. This PR has the template use a dummy zip file when the stack's stage name indicates that it's being compiled for unit tests.
This PR does the following:
1. Adds a dummy lambda zip file `emily/cdk/test/assets/empty-lambda.zip` 
2. Creates a `constants.ts` file that defines the unit test stagename so it's consistent across files.
3. Changes the template to use the dummy lambda when being compiled for unit tests
4. Changes the unit tests to expect the new stagename.
5. Optimizes imports. 
6. Changes the `cdk` command to use the local package
Relates to a reported issue that is too small to file a ticket for.
=> Setup cdk unit tests to be independent of lambda compilation.

Cargo.lock, Cargo.toml, signer/Cargo.toml, signer/src/error.rs, signer/src/lib.rs, signer/src/utxo.rs
Closes https://github.com/stacks-network/sbtc/issues/75.
We need to take a set of deposit and withdrawal requests and turn them into BTC transactions that can be signed by the signers. This PR gets us part of the way there.
This is new code that takes the current state of the signers UTXO, the current market rate in sats-per-vbyte, along with outstanding deposit and withdrawal requests and creates a set of BTC transactions.
There are several things worth noting though:
1. The UTXO output scripts for withdrawals are pay-to-witness-public-key-hash (P2WPKH) outputs. I think this is fine, since it's probably okay to a assume our users have native segwit addresses but I don't know about assuming the same for taproot addresses. In the future, maybe the user can decide?
2. I have not implemented …
=> feat: construct BTC transactions

Cargo.lock, Cargo.toml, signer/Cargo.toml, signer/src/ecdsa.rs, signer/src/lib.rs, signer/src/message.rs
closes #105 
This PR introduces signing and validation logic for signer messages. As part of this change, the `signer_public_key` and `signature` fields of the `SignerMessage` type has been moved to the new `Signed` wrapper type to allow for ergonomic handling of signatures.
=> feat: Signer message signing and validation

LICENSE, README.md
- Add GPL License
- Add GPL License badge to `README.md`
=> feat: GPL V3 License

.github/workflows/unit-tests.yaml
Mistakenly pushed #133 before renaming the rust github workflow. This renames those tests.
=> task: Rename Rust GitHub workflow to generic Test workflow

Cargo.lock, Cargo.toml, signer/Cargo.toml, signer/src/codec.rs, signer/src/ecdsa.rs, signer/src/lib.rs, signer/src/message.rs
closes #106
This PR introduces serialization logic for Signer messages by
1. Defining the `Encode` and `Decode` traits, which denote the canonical encoding format for signer messages, with a blanket implementation using Bincode for all types implementing serde::Serialize and serde::Deserialize.
2. Deriving `serde::Serialize` and `serde::Deserialize` for all message types.
=> feat: Signer message serialization

Cargo.lock, signer/Cargo.toml, signer/src/ecdsa.rs, signer/src/lib.rs, signer/src/network.rs, signer/src/network/in_memory.rs
closes #107 and #108 
This PR defines the client interface for the signer network through the `signer::network::Client` trait. It also provides an in-memory implementation of a signer network by wrapping a `tokio::sync::broadcast` channel for illustrative and testing purposes.
=> feat: Signer network interface & in-memory implementation

Cargo.lock, blocklist-client/Cargo.toml, blocklist-client/src/main.rs, signer/Cargo.toml, signer/src/codec.rs, signer/src/ecdsa.rs
Closes https://github.com/stacks-network/sbtc/issues/142, which started from this thread https://github.com/stacks-network/sbtc/pull/137#discussion_r1595542013.
The signer binary was supposed to be called `signer` to begin with, this PR makes it so.
Renames the signer binary/library and updates the dependencies.
=> build: rename sbtc-signer binary to signer

signer/src/error.rs, signer/src/utxo.rs, signer/tests/integration/regtest.rs, signer/tests/integration/utxo_construction.rs
Closes https://github.com/stacks-network/sbtc/issues/152.
Each transaction input needs to be accompanied by a signed digest before being submitted to the bitcoin network. It is not obvious which steps need to be taken to construct this digest, so this PR adds helper functions that simplifies their creation.
Provide context on how tests should be performed.
1. There is already an integration test that constructs a transaction, signs it, and submits it to the bitcoin network. This PR updates that test to use the new helper functions. If bitcoind accepts our transaction, then things are likely constructed correctly.
=> feat: simplify peg-in transaction signing

.gitignore, emily/api-definition/package.json
I noticed that `package-lock.json` was generated when `make build` ran, and that's due to this invocation of `npx @openapi...`. `npx` uses `npm` under the hood, and the `npx` command is essentially the same as "npm install ... " and then running that bin script. Because `@openapitools/openapi-generator-cli` is already installed as a devDependency, you can just use the bin script's name inside a package.json script.
To verify, run `make install` and `make build` and validate that package-lock.json isn't re-created.
=> fix: prevent package-lock.json from being built

.github/workflows/contract-tests.yaml, contracts/docs/README.md, contracts/docs/sbtc-bootstrap-signers.md, contracts/docs/sbtc-deposit.md, contracts/docs/sbtc-registry.md, contracts/package.json, contracts/tests/clarigen-types.ts, pnpm-lock.yaml
This PR does two things:
- Updates the `pnpm build` command in `contracts` to build Clarigen docs & types. This is implicitly included in `make build`.
- Adds a CI step to check that docs & types were built and pushed
The motivation is that it's easy to forget to run `clarigen && clarigen docs` before pushing, and doing so can introduce git changes in other branches, or even end up with type or runtime errors.
You can see the CI in action:
- The first commit only adds the CI workflow update, but doesn't include updated types. [CI fails and an error is shown](https://github.com/stacks-network/sbtc/actions/runs/9130353433/job/25107067998)
- The second commit pushes the types that were created with `make build`, and CI passes.
=> Update contract CI to ensure docs & types are built

Cargo.lock, signer/Cargo.toml, signer/src/utxo.rs, signer/tests/integration/rbf.rs, signer/tests/integration/regtest.rs, signer/tests/integration/utxo_construction.rs
Closes https://github.com/stacks-network/sbtc/issues/68.
This is a follow-up to https://github.com/stacks-network/sbtc/pull/169, that makes sure that we can Replace-by-Fee (RBF) transaction packages. I thought there was a chance that we won't be able to do it, given the policy described in bitcoin-core [bitcoin/doc/policy/packages.md](https://github.com/bitcoin/bitcoin/blob/ecd23656db174adef61d3bd753d02698c3528192/doc/policy/packages.md#package-mempool-acceptance-rules)
> No transaction in a package can conflict with a mempool transaction. Replace By Fee is currently disabled for packages. (#20833)
But the solution is simple, don't submit transaction packages and instead submit transactions individually. The noteworthy part about this is that now the fees users pay is highly dependent on …
=> feat: fee handling of RBF transaction packages

signer/Cargo.toml, signer/src/lib.rs, signer/src/testing.rs, signer/src/utxo.rs, signer/tests/integration/rbf.rs, signer/tests/integration/regtest.rs, signer/tests/integration/utxo_construction.rs
Closes https://github.com/stacks-network/sbtc/issues/65.
The current code that generates peg-in/-out BTC transactions always includes the incoming request in the BTC package, regardless of the user specified max fee. This PR changes this behavior to respect the max fee given by the user, excluding them if the fee rate is too high compared to their max fee.
This PR uses a conservative heuristic to exclude requests from the peg-in/-out BTC transaction where we are guaranteed to respect their max fee. At the same time, there may be a more optimal way of figuring out whether we are respecting their fee since the code here assumes the worst (the most the request will have to pay given the market fee rate) and excludes the transaction based on that. But I don't see a way around that.
1. Add …
=> feat: respect users' max fees

signer/src/utxo.rs, signer/tests/integration/rbf.rs
Closes https://github.com/stacks-network/sbtc/issues/182.
Currently, each request in a BTC transaction pays an equal portion of the total transaction fee. This PR modifies this approach by making the fee proportional to the size of each input or output UTXO relative to the total size of all UTXOs involved in the transaction[^1]. For instance, if a transaction incurs a 1000 sat fee and includes one deposit UTXO and one withdrawal UTXO—where the deposit UTXO constitutes 70% of the total UTXO size—the deposit will bear 700 sats of the fee, and the withdrawal will cover the remaining 300 sats.
[^1]: Note that these calculations exclude the signers' UTXOs when computing the a request UTXO's proportion of the weight.
1. Change the fee computation calculation to be proportional to weight.
The …
=> feat: charge fees based on virtual size

signer/src/utxo.rs, signer/tests/integration/rbf.rs, signer/tests/integration/regtest.rs, signer/tests/integration/utxo_construction.rs
Closes https://github.com/stacks-network/sbtc/issues/67.
We needed one additional integration test with `bitcoind` to assess BTC withdrawal transactions.
This update introduces an integration test that verifies the functionality of the signers' BTC transactions for withdrawals. Specifically, we ensure that:
1. The transaction is accepted by bitcoin-core.
2. The signer's UTXO amount is correctly reduced by the withdrawal amount.
3. The amount sent to the intended address equals the withdrawal amount minus the BTC transaction fee.
4. The withdrawal address can spend those coins.
=> test: add BTC withdrawal integration tests

Cargo.lock, Cargo.toml, signer/Cargo.toml, signer/src/message.rs, signer/src/message/testing.rs
Closes #172 
This PR adds fields for the `SignerDepositDecision` and `SignerWithdrawDecision` message variants, along with tests to ensure that these are signable and encodable.
=> feat: SignerDepositDecision and SignerWithdrawDecision payloads defined

signer/src/message.rs, signer/src/message/testing.rs
Closes #174 
This PR adds fields for the `BitcoinTransactionSignRequest` and `BitcointransactionSignAck` message variants, along with tests to ensure that these are signable and encodable.
Note: This PR is currently based on #189 because it uses test utilities from it.
=> feat: BitcoinTransactionSignRequest and BitcoinTransactionSignAck payloads defined

.github/workflows/unit-tests.yaml, contracts/Clarinet.toml, contracts/contracts/sbtc-withdrawal.clar, contracts/deployments/default.simnet-plan.yaml, contracts/tests/clarigen-types.ts, contracts/tests/helpers.ts, contracts/tests/sbtc-registry.test.ts, contracts/tests/sbtc-withdrawal.test.ts
- (Partially) Closes https://github.com/stacks-network/sbtc/issues/95
This PR is essentially two things:
- Validation for the `recipient` param (using the same logic and structure as PoX)
- A user-facing function for initiating a withdrawal request
At the moment, this doesn't actually convert the user's sBTC into locked sBTC, as we don't have that contract yet.
This also builds on top of #167 because I added a few helpers in there that I wanted to use in here.
=> feat: initiate-withdrawal-request

devenv/local/docker-compose/docker-compose.yml, devenv/local/docker-compose/electrs/docker/entrypoint.sh
This PR contains a quick fix which allows electrum to be able to communicate with the mempool backend in the devnet
Changes:
- Electrs now listens to all IPs (0.0.0.0) instead of just (127.0.0.1)
- Switched `MEMPOOL_BACKEND: "none" ` --> `MEMPOOL_BACKEND: "electrum"`. Mempool now uses electrum along with BTC RPC.
=> Fixing electrs and mempool backend communication errors

signer/src/utxo.rs, signer/tests/integration/rbf.rs, signer/tests/integration/utxo_construction.rs
Closes https://github.com/stacks-network/sbtc/issues/130.
Deposit requests are BTC transactions with taproot UTXOs to an address with no key-spend route. Specifically, we use a key-spend public key with no known private key. This PR implements the change where we expect the taproot address to use such an public key. We choose the specific X-coordinate mentioned in BIP-0341 as the public key, which has an X-coordinate set to the SHA256 of the generator G.
1. Add a function that returns a public key for an address with no known public key.
2. Expect all taproot key-spend public keys to use this address from (1). This was done in f7173a4e56e2baa26eb206e3e50a31632c6666f3, but I'm not sure if we want the flexibility of the previous code.
I checked that the point in BIP-0341 is indeed on the …
=> feat: use unspendable taproot public keys for deposits

devenv/local/k8s/build.sh, devenv/local/k8s/custom-k8s-docker-builds/electrs/docker/Dockerfile, devenv/local/k8s/custom-k8s-docker-builds/electrs/docker/entrypoint.sh, devenv/local/k8s/down.sh, devenv/local/k8s/tests/devnet-liveness.sh, devenv/local/k8s/up.sh, devenv/local/k8s/utils/port-forward-containers.sh, devenv/local/k8s/yamls/deployments/electrs-deployment.yaml, devenv/local/k8s/yamls/deployments/mariadb-deployment.yaml, devenv/local/k8s/yamls/deployments/mempool-backend-deployment.yaml, devenv/local/k8s/yamls/deployments/mempool-frontend-deployment.yaml, devenv/local/k8s/yamls/services/services.yaml
Closes #211 
This PR contains the necessary components in K8s to get the Electrs, MariaDB, Mempool FE & BE running locally
This contains all the deployments, services, tests, and Docker build files for each of the components. More details are listed in #211  
Please follow the instructions at: `devenv/local/k8s/README.md`
After completing the `Installation` section, please run the following:
[1] `minikube start`
[2] `sh build.sh`
[3] `sh up.sh`
[4] `sh ./tests/devnet-liveness.sh`
[5] `sh down.sh`
[6] `minikube stop`
In order for this PR to pass, the tests in `devnet-liveness.sh` should pass
=> K8s Artifacts for Electrs, MariaDB, Mempool FE & BE

devenv/local/docker-compose/docker-compose.yml
There are some env vars which were not necessary since they are already used during build time.
For example: 
- MINER_KEY
- MY_HTTP_AUTH_TOKEN
- SIGNER_ENDPOINT
- BTC_NODE_RPC_HOST
- BTC_NODE_RPC_USER
- BTC_NODE_RPC_PASSWORD
- LOCAL_PEER_SEED
=> Devnet Fix - Cleanup of unnecessary env vars in Docker Compose

signer/Cargo.toml, signer/src/block_observer.rs, signer/src/lib.rs, signer/src/message/testing.rs, signer/src/storage.rs, signer/src/storage/in_memory.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing.rs, signer/src/testing/dummy.rs, signer/tests/integration/postgres.rs
closes #120 
This PR introduces the block observer event loop, with placeholder logic referencing follow-up tickets for the remainder of the block observer functionality. The current observer only writes the bitcoin blocks.
In addition to the event loop, the PR also adds:
* In-memory storage implementation (needed for tests).
* Bitcoin block generation logic for tests.
* Missing transaction type in the `storage::model` (unrelated broken window fix).
=> feat: Block observer event loop skeleton

Cargo.lock, Cargo.toml, blocklist-client/README.md, signer/Cargo.toml, signer/README.md, signer/src/lib.rs, signer/src/network.rs, signer/src/storage/postgres.rs, signer/src/transaction_signer.rs
closes #221 
The documentation can be rendered locally using `cargo doc --open`. The mermaid charts should be rendered in the docs thanks to [aquamarine](https://github.com/mersinvald/aquamarine).
=> docs: Document design for transaction signer event loop

contracts/contracts/sbtc-registry.clar, contracts/contracts/sbtc-token.clar, contracts/contracts/sbtc-withdrawal.clar, contracts/tests/clarigen-types.ts, contracts/tests/sbtc-withdrawal.test.ts
This uses the new sBTC token contract to properly lock the user's sBTC when they initialize a withdrawal request.
=> feat: lock sBTC when initializing withdrawal

.sqlx/query-3446a823d60a644dc58bc0c36ba256747ba46b9441072ad8a13c2a6703974a45.json, .sqlx/query-3f0879dab4417cf80f9287fe579c2c6b66f3ac4cc3fe4845ecc4cfe85b4c8e8d.json, .sqlx/query-ac71ab51277e5afa623340de33981eb58d2ae5da602531f49d49c62d711ba6ed.json, contracts/tests/clarigen-types.ts, signer/migrations/0003__create_tables.sql, signer/src/block_observer.rs, signer/src/error.rs, signer/src/storage.rs, signer/src/storage/in_memory.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/storage/model.rs, signer/src/transaction_signer.rs, signer/tests/integration/postgres.rs
closes #234 
This PR adds a rough skeleton implementation for the transaction signer event loop with the logic to make and persist decisions for pending requests, including a unit test for the handling of deposit requests.
The most important changes are the additions to `transaction_signer.rs`, whereas most of the remaining changes are database queries and updates to data generation logic for tests.
=> feat: Skeleton for transaction signer event loop with request decision handling

signer/src/block_observer.rs, signer/src/error.rs
Closes #229 
Currently based on PR #248
=> feat: Modify block observer to use the top-level error::Error type

contracts/contracts/sbtc-deposit.clar, contracts/tests/clarigen-types.ts, contracts/tests/sbtc-deposit.test.ts, contracts/tests/sbtc-token.test.ts
This PR introduces a 'complete-deposits-wrapper' that address the ability for signers to submit multiple deposits requests at once.
The motivation for this PR was to close out #86.
This is a new feature change that wraps around existing functionality.
No.
No.
Changes are tested using ClarinetSDK.
=> Deposit accept many

Cargo.toml, contracts/tests/sbtc-withdrawal.test.ts, docker-compose.test.yml, signer/.sqlx/query-3446a823d60a644dc58bc0c36ba256747ba46b9441072ad8a13c2a6703974a45.json, signer/.sqlx/query-3f0879dab4417cf80f9287fe579c2c6b66f3ac4cc3fe4845ecc4cfe85b4c8e8d.json, signer/.sqlx/query-4d8b40e94cb12a4fcda6b08063bc247e2229d864bc6c6c6a89f25c91ba60f840.json, signer/.sqlx/query-54884a5f0278765c3d5a3890f9a6cdc60ed352883e037748295d62bcab94ae86.json, signer/.sqlx/query-6678744f83dfa4708706937f9c88ca445f11e846c36995ed0b0754928096da99.json, signer/.sqlx/query-7e247d7abf23d1386a01457bdf87ed9213df9782635a2a8cfe84e27ec8750784.json, signer/.sqlx/query-ac71ab51277e5afa623340de33981eb58d2ae5da602531f49d49c62d711ba6ed.json, signer/.sqlx/query-e2bd6bcf452d37dee4e0c9b466272e2b2c8a7295350201ecf1fa7ccad24287a8.json, signer/.sqlx/query-e4f7cae570f67835407d9a4fddae531b354e355ac374c26b5d2d6fbd9660a2e3.json, signer/src/block_observer.rs, signer/src/error.rs, signer/src/storage.rs, signer/src/storage/in_memory.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/storage/model.rs, signer/src/transaction_signer.rs, signer/tests/integration/postgres.rs
Closes https://github.com/stacks-network/sbtc/issues/212.
We need to persist stacks block headers and sBTC related Stacks transactions to the database. This PR includes functions for writing such data given a Nakamoto stacks block.
1. Rework the `DbRead` and `DbWrite` traits to be a little simpler by only taking a reference to `self` in the functions that need implementing. Although taking `self` allows for more flexibility, we don't actually need or use it, so this change allows for some simplification.
2. Only implement the above traits for the `SharedStore` and the `PgStore`.
3. Add a function for checking for the existence of a stacks block in the database.
4. Add a function for writing stacks blocks -- both the header and the transactions -- to the database.
* I'm pretty sure the …
=> feat: writing stacks block

signer/src/block_observer.rs, signer/src/config.rs, signer/src/config/default.toml, signer/src/stacks_api.rs, signer/src/storage/postgres.rs
Closes https://github.com/stacks-network/sbtc/issues/242.
We need functions for filling in Stacks Nakamoto blocks in case we missed some. This PR adds such functionality.
1. Redo the `StacksInteract` trait to support fetching "unknown" ancestors.
2. Add a basic integration test that work with nakamoto is running. Since we do not have nakamoto running in CI, this test is ignored.
1. The new `StacksInteract::fetch_unknown_ancestors` API feels kludgy, but I'm not sure how to make it not-so.
2. The implementation of the `fetch_unknown_ancestors` function fetches blocks by tenure, which may include many more blocks than is necessary to get only "unknown" blocks. If this is a problem, it's very easy to change the function to fetch things block by block.
3. The implementation of the …
=> feat: support backfilling the stacks blockchain

signer/src/testing/dummy.rs
=> feat: Proper coinbase generation

signer/src/stacks/contracts.rs, signer/tests/integration/contracts.rs, signer/tests/integration/main.rs
Closes https://github.com/stacks-network/sbtc/issues/230.
We need to make it possible to make the contract call that mints sBTC. This PR adds structs that simplify construction of a stacks transaction that calls the `complete-deposit-wrapper` function from our `sbtc-deposit.clar` contract.
1. Add a struct that implements the `AsContractCall` trait that allows us to easily make the `complete-deposit-wrapper` contract call.
We add a test that checks that we do not panic when creating the `TransactionContractCall`. If this test fails, then we know that we have a typo in the contract or function names.
Note: I've been feeling conflicted about using `expect` and `unwrap` in the code base. In this case, there is an implicit `unwrap` but I add a test that ensures that we cannot panic at runtime. …
=> feat: support sBTC mint transactions

.generated-sources/emily/openapi/build.rs, .generated-sources/emily/openapi/emily-openapi-spec.json, emily/handler/src/api/handlers/chainstate.rs, emily/handler/src/api/handlers/deposit.rs, emily/handler/src/api/handlers/mod.rs, emily/handler/src/api/handlers/withdrawal.rs, emily/handler/src/api/routes/chainstate.rs, emily/handler/src/api/routes/deposit.rs, emily/handler/src/api/routes/health.rs, emily/handler/src/api/routes/mod.rs, emily/handler/src/api/routes/withdrawal.rs
Resolves #272 
This PR does the following:
1. Adds the `chainstate` and `withdrawal` endpoints to the warp paths.
2. Adds dummy event handlers for the the `chainstate` and `withdrawal` endpoints
3. Adds `utoipa` annotations to every handler
4. Updates the `build.rs` script for the Emily openapi spec
**Bonus:** Minor fix to `utoipa` annotations for the deposit endpoint so that `GET` api calls are said to return `200` as opposed to `201`.
=> 272 feature add withdrawal and chainstate endpoints

contracts/contracts/sbtc-registry.clar, contracts/contracts/sbtc-withdrawal.clar, contracts/tests/clarigen-types.ts, contracts/tests/sbtc-withdrawal.test.ts
This PR deals with #95, #96, & #97 with the focus of initiating, accepting & rejecting withdrawal requests. As a signer, once completed, I want to mark a withdrawal as completed on-chain & therefore burning the sBTC.
New feature planned in #95 that comes from the sBTC Clarity documentation.
No.
No.
Six different unit tests included here that can be ran CDing into 'contracts' & running 'pnpm test.'
=> [Clarity] Complete Accepted Withdrawal Request

.github/workflows/contract-tests.yaml, .github/workflows/unit-tests.yaml, Dockerfile, README.md
I don't think we use java anymore. Also, let's update the version of pnpm that we use locally.
=> ci: remove java from CI and bump pnpm version

signer/src/storage.rs, signer/src/storage/in_memory.rs, signer/src/storage/postgres.rs, signer/src/testing/transaction_signer.rs, signer/src/transaction_signer.rs, signer/tests/integration/transaction_signer.rs
closes #256 
This PR adds a few utility functions for the transaction validation, but since the validation logic depends on transaction parsing logic we'll leave the validation to a follow-up
=> feat: Transaction signer acknowledging bitcoin transaction sign requests

.github/workflows/contract-tests.yaml, .github/workflows/unit-tests.yaml
This should fix CI issues.
Specifying the pnpm version causes an issue where the version specified in the action and the by the `package.json` don't match. This is an example of a job where CI failed because of this kind of version mismatch: https://github.com/stacks-network/sbtc/actions/runs/9803820830/job/27070555360.
The original need to update started with random CI failures (like in this [CI run](https://github.com/stacks-network/sbtc/actions/runs/9803450411/job/27069632164#step:4:14)), and the solution was noted in https://github.com/pnpm/pnpm/issues/6424.
=> ci: bump the pnpm action version

signer/src/stacks/api.rs
Closes https://github.com/stacks-network/sbtc/issues/291.
Adds support for submitting transactions to a stacks node.
1. Adds a function to the `StacksClient` type for submitting a transaction to a node.
2. Minor refactor of the `StacksClient::get_tenure` function.
There are no tests for this function, this will happen as part of https://github.com/stacks-network/sbtc/issues/263
=> feat: support submitting stacks transactions

signer/src/error.rs, signer/src/stacks/api.rs
Closes https://github.com/stacks-network/sbtc/issues/301. Add a function that gets account information, including the nonce.
* Adds a function that fetches the account info from a stacks node.
There is an integration test that does not run in CI. It was tested against a local stacks node.
=> feat: fetching nonce from stacks node

Cargo.lock, Cargo.toml, signer/Cargo.toml, signer/src/error.rs, signer/src/message.rs, signer/src/storage.rs, signer/src/storage/in_memory.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/dummy.rs, signer/src/testing/message.rs, signer/src/testing/transaction_signer.rs, signer/src/transaction_signer.rs, signer/tests/integration/transaction_signer.rs
closes #257 
This PR extends the transaction signer to be able to participate in DKG rounds and signing rounds. To achieve this, each transaction signer keeps track of a set of WSTS state machines identified by the TXID of the transaction they are signing. These state machines are created from persisted DKG shares upon a sign request.
=> feat: Transaction signer responding to WSTS messages

signer/src/error.rs, signer/src/storage/model.rs, signer/src/testing/transaction_signer.rs, signer/src/transaction_signer.rs, signer/tests/integration/transaction_signer.rs
closes #258 
This PR extends the transaction signer in testing with a mpsc channel, signalling when decisions are received and persisted. This allows test cases to wait for a transaction signer to receive and process other signer decisions, which previously wasn't possible - thus removing an inherently flaky and slow timeout from our tests.
=> feat: support waiting for a transaction signer to finish processing pending messages in tests

contracts/contracts/sbtc-bootstrap-signers.clar, contracts/contracts/sbtc-registry.clar, contracts/docs/sbtc-bootstrap-signers.md, contracts/tests/clarigen-types.ts, signer/src/error.rs, signer/src/lib.rs, signer/src/stacks/contracts.rs, signer/src/stacks/wallet.rs, signer/tests/stacks/stacks-node-config.toml
Closes https://github.com/stacks-network/sbtc/issues/307.
I believe this is the last contract call that we need to support.
* Bump the maximum number of signers to 128 from 15. @hstove @setzeus thoughts (it's this commit d6ac6ec046ef0bb8c1b22fba213dfdd3dc24c4e2)?
* Update the address hash mode to match the hash mode assumed in the clarity contracts.
* Add a constant in the signer codebase that sets the cap on the number of signers.
* Add an implementation of a struct that we can use to easily rotate the Signers' multi-sig wallet.
I added a test that checks that we do not error when creating the struct under common circumstances.
=> feat: support key rotation contract calls

contracts/contracts/sbtc-bootstrap-signers.clar, contracts/docs/sbtc-bootstrap-signers.md, signer/src/error.rs, signer/src/stacks/api.rs, signer/src/stacks/contracts.rs, signer/src/stacks/wallet.rs, signer/src/storage/postgres.rs, signer/src/testing/wallet.rs, signer/tests/integration/contracts.rs
Closes https://github.com/stacks-network/sbtc/issues/264.
We have a bunch of code for creating and signing stacks contract call transactions. This PR adds tests for whether these transactions will be accepted by a stacks node post-Nakamoto.
* Update comments/documentation in a sBTC clarity contract. This became outdated after https://github.com/stacks-network/sbtc/pull/308.
* Updated the documentation of fields in some Stacks structs. Specifically, the nonce returned by `GET /v2/account/<principal>` request is the next nonce.
* Combine the `SignerWallet` and `SignerStxState` structs into one.
* Add a tests that checks whether each our contract calls will be accepted by a stacks node.
The tests that are added here are not run in CI, since we do not have Nakamoto running there yet. Tests …
=> ci: integration test stacks smart contracts

Cargo.lock, common/Cargo.toml, common/src/deposits.rs, common/src/lib.rs, signer/src/utxo.rs, signer/tests/integration/utxo_construction.rs
Use the following template to create your pull request
Closes https://github.com/stacks-network/sbtc/issues/329.
1. Add a function that can construct a deposit script from the deposit info (the signers' public key, the recipient address, and the max fee).
2. Add a function that can construct a BTC address given the deposit script variables.
3. Saw that the `utxo::DepositRequest` struct had a typo in one of the field names, corrected it.
The unit tests here are okay
=> feat: construct bitcoin deposit addresses

common/src/deposits.rs
Closes https://github.com/stacks-network/sbtc/issues/327.
- Add a function that can parse a deposit script and extract the relevant pieces of information.
The tests check that the parser function is an inverse of the `DepositScriptInputs::deposit_script` function.
=> feat: add a deposit script parsing function

contracts/contracts/sbtc-registry.clar, contracts/contracts/sbtc-token.clar, contracts/tests/clarigen-types.ts, contracts/tests/sbtc-registry.test.ts, contracts/tests/sbtc-token.test.ts, contracts/tests/sbtc-withdrawal.test.ts
- Closes #347 
This PR finishes the work that @setzeus started. Initially, the `sbtc-registry` utilized a placeholder function for validating contract callers, because we didn't yet have the data structures in place to properly handle things. Now, those data structures are in place, but the `validate-caller` function wasn't using them.
=> Remove placeholder `validate-caller` clarity function

common/src/deposits.rs, common/src/lib.rs
Closes https://github.com/stacks-network/sbtc/issues/328.
This PR is analogous to https://github.com/stacks-network/sbtc/pull/334, which parsed the deposit script and extracted the relevant variables for validation. Here we parse the reclaim script for validation.
Although the reclaim script is conceptually simpler, since there is only one variable that we care about, extracting that variable happens to be slightly more annoying due to how inputs to `OP_CSV` (and `OP_CLTV`) handle their inputs in bitcoin-core. I try to add enough documentation about this.
* Add a function that can parse a reclaim script and extract the relevant pieces of information (the lock time and the other pieces).
* I basically duplicated some functions from rust-bitcoin here (I needed to modify them slightly). The …
=> feat: add reclaim script parsing function

common/src/deposits.rs, signer/src/utxo.rs
Closes https://github.com/stacks-network/sbtc/issues/330.
The last part (or second-to-last part) of "BTC deposit transaction analysis" is validating that the transaction is "valid". Basically, we check that the deposit and reclaim scripts in the transaction follow our proscribed formats.
1. A slight refactor involving the parsing functions https://github.com/stacks-network/sbtc/pull/344 and https://github.com/stacks-network/sbtc/pull/334.
2. Add a function that takes in a BTC transaction encoded as a hex string and makes sure that the relevant UTXO matches what was sent in the `CreateDepositRequest` (the object from the [Emily API LLD](https://docs.google.com/document/d/13AN9GdLfPYKKPkeHNU4niq_CyJCDxFR7DGBLzLc5gxU/edit#heading=h.hbinuw8xakzd)).
3. Update some of the comments in the signer …
=> feat: validate bitcoin deposit transactions

signer/src/stacks/contracts.rs, signer/tests/integration/contracts.rs, signer/tests/integration/postgres.rs
Closes https://github.com/stacks-network/sbtc/issues/332.
* Update the contract-call struct to support any stacks principal as the recipient.
* Add integration test cases that exercise the contract principal case.
I ran the integration tests locally, using the same setup as in https://github.com/stacks-network/sbtc/pull/311, and tests passed.
Note that, similar to standard recipients, you do not need to "materialize" or "deploy" the smart contract before it can accept STX or other fungible tokens.
=> feat: support contract principals in complete-deposit contract calls

signer/src/block_observer.rs, signer/src/error.rs, signer/src/stacks/api.rs, signer/src/stacks/contracts.rs, signer/tests/integration/contracts.rs, signer/tests/integration/postgres.rs
Closes https://github.com/stacks-network/sbtc/issues/233.
We need the current priority  mempool fees for stacks transactions. This PR adds a function that uses the `POST /v2/fees/transaction` endpoint on stacks-core for this.
All fees returned are the high-priority fee amount (not the fee rate). And the implementation for estimating fees in the trait falls back on the high-priority STX transfer fee in the event that the node cannot estimate fees for the transaction.
* Add a function that estimates transaction fees (for contract calls or otherwise).
* Add a function to the `StacksInterface` trait for estimating fees, along with a "robust" implementation that falls back to the STX transfer fee estimate if the node does not know how much the particular transaction will cost.
This PR adds an …
=> feat: support estimating contract calls fees

Cargo.lock, Cargo.toml, sbtc/Cargo.toml, sbtc/src/deposits.rs, sbtc/src/error.rs, sbtc/src/lib.rs, sbtc/src/rpc.rs
Closes https://github.com/stacks-network/sbtc/issues/363. This PR adds a bitcoin-core and electrum server implementation for fetching the deposit transaction (and validating it).
The only reason why this adds two implementations was because of how I went about working on it. I finished the bitcoin-core RPC implementation and then realized that using bitcoin-core's [getrawtransaction RPC](https://bitcoincore.org/en/doc/27.0.0/rpc/rawtransactions/getrawtransaction/) might not be ideal. For it to work as intended, it requires the `-txindex` flag to be `1`, which might not be setup on the signers' bitcoin-core (no idea one way or the other). Also, we plan on having electrum server set up anyway, and that offers similar functionality but without the requirement of the `-txindex` flag being set …
=> feat: extract deposit request transactions

signer/src/block_observer.rs, signer/src/stacks/api.rs, signer/tests/integration/contracts.rs
Closes https://github.com/stacks-network/sbtc/issues/366. And is a follow-up to https://github.com/stacks-network/sbtc/pull/361.
* Cap the maximum fee that signers will pay for a transaction to 10 STX.
* Allow the fee priority to be selected by the caller of the estimation function.
The existing tests we updated to support the new functionality.
=> feat: robust stacks transaction fee estimation

sbtc/src/deposits.rs, sbtc/src/error.rs, sbtc/src/rpc.rs, sbtc/tests/integration/rpc.rs, signer/src/fees.rs, signer/tests/integration/rbf.rs, signer/tests/integration/utxo_construction.rs
Closes https://github.com/stacks-network/sbtc/issues/160.
During the design phase, we aligned on using electrum as a source for fee estimates. This PR adds two implementations, one from electrum and another from bitcoin-core. The bitcoin-core implementation makes testing easier, since some implementations of electrum use bitcoin-core's `estimatesmartfee` RPC under the hood.
* Add an implementation that estimates fees using electrum.
* Add an implementation that estimates fees using bitcoin-core.
* Update the `fees` module in the signer create to return a `FeeEstimate` type.
* Updated the error messages in the `sbtc` crate, I forgot to do this in an earlier PR.
This PR adds an integration test for the `electrum` and `bitcoin-core` estimate fee implementations, but I stopped short of making …
=> feat: add electrum for fee estimates

.generated-sources/emily/openapi/build.rs, .generated-sources/emily/openapi/emily-openapi-spec.json, emily/handler/src/api/handlers/mod.rs, emily/handler/src/api/handlers/testing.rs, emily/handler/src/api/routes/mod.rs, emily/handler/src/api/routes/testing.rs, emily/handler/src/common/error.rs, emily/handler/src/database/accessors.rs
Closes: #375 
Adds a `/testing/wipe` endpoint to the Emily API that wipes the databases.
Adds a `/testing` endpoint that is only created when the `testing` feature is activated which can wipe the databases.
The following are added in this PR:
- A database accessor function that wipes a database
- A database accessor that gets all entries in a table
- A `testing` endpoint route
- A `testing` endpoint route handler
Tested locally by populating the database with the sequence:
```bash
make emily-integration-env-up
```
```bash
make emily-populate-database
curl "localhost:3000/withdrawal?status=pending&pageSize=1000" | jq
curl "localhost:3000/deposit?status=pending&pageSize=1000" | jq
curl -X POST "localhost:3000/testing/wipe"
curl "localhost:3000/withdrawal?status=pending&pageSize=1000" | jq …
```
=> Add `testing` endpoint to emily api

sbtc/src/deposits.rs, sbtc/src/error.rs, sbtc/src/rpc.rs, sbtc/tests/integration/rpc.rs, sbtc/tests/integration/validation.rs, signer/src/block_observer.rs, signer/src/fees.rs, signer/src/storage.rs, signer/src/storage/in_memory.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/tests/integration/postgres.rs
Closes: https://github.com/stacks-network/sbtc/issues/203.
* Rename structs and to conform more closely to our specs.
* Add a new storage trait function, `write_deposit_requests`, that stores deposit requests.
* Implement the `write_deposit_requests` function for postgres and the in-memory thing.
There are unit tests for the new block observer logic and an integration test for the query.
=> feat: extract deposit requests in block observer

Cargo.lock, emily/handler/Cargo.toml, emily/handler/src/database/accessors.rs, emily/handler/tests/integration/endpoints/chainstate.rs, emily/handler/tests/integration/endpoints/deposit.rs, emily/handler/tests/integration/endpoints/withdrawal.rs, emily/handler/tests/integration/util/mod.rs
Closes: #392 
Makes the emily integration tests self containing by wiping the database before each integration test.
The tests still use the underlying client to the `TestClient` instead of the methods in the `TestClient` for two reasons:
1. To make the tests more transparent when they fail for these unit - like tests.
2. To reduce the number of changes in this single PR.
Adds setup function to each of the endpoint tests.
Note I opted to have a somewhat-useless `client.teardown().await;` call to every integration test to further make sure that we aren't leaving anything behind, and to make the `teardown` function available to more features going forward if there becomes more to teardown.
I'm all for redundancy if it makes what our tests do more obvious.
Run tests with the following:
1. …
=> feat: Make emily integration tests self containing.

Cargo.lock, Cargo.toml, docker-compose.test.yml, sbtc/src/deposits.rs, sbtc/src/testing/regtest.rs, signer/Cargo.toml, signer/src/error.rs, signer/src/lib.rs, signer/src/zmq.rs, signer/tests/integration/main.rs, signer/tests/integration/zmq.rs, signer/tests/service-configs/bitcoin.conf
Closes: https://github.com/stacks-network/sbtc/issues/383.
The electrum client that we have for rust requires you to poll the server for bitcoin blocks. While not terrible, using the ZeroMQ interface on bitcoin-core gives us real-time notifications, and allows us to remove electrum server as a requirement for running the signer application.
* Add structs subscribe to bitcoin-cores ZeroMQ notification interface for block and block hash notifications.
* Add an integration test that listens to bitcoin-core messages and checks the new code.
The two integration tests check the new logic that was added here. It does not validate the messages received and does not reproduce the logic laid out in the bitcoin docs for what happens during a reorg. That we should do later in …
=> feat: use bitcoin-core as the block notifier

Cargo.lock, emily/handler/tests/integration/complex/reorg.rs, signer/migrations/0003__create_tables.sql, signer/src/bitcoin/utxo.rs, signer/src/block_observer.rs, signer/src/error.rs, signer/src/stacks/contracts.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/dummy.rs, signer/src/testing/wallet.rs, signer/src/transaction_signer.rs, signer/tests/integration/postgres.rs
Closes https://github.com/stacks-network/sbtc/issues/204.
We can probably remove the `tweaked_aggregate_key` column from the `dkg_shares` table now.
* Add a `script_pubkey` column to the `dkg_shares` table. This makes it simple for us to find BTC transactions that the signers have sent. The alternative is to assume that witness program version is always 1, and derive the `scriptPubKey` from the tweaked public key. It also makes it easy for us to find donations for https://github.com/stacks-network/sbtc/issues/353.
* Add a trait for converting `p256k1` types and `rust-secp256k1` types to the signers' `scriptPubKey`.
* Implement the `BlockObserver::extract_sbtc_transactions` function.
* Add function for writing bitcoin transactions into the database.
There are unit tests for the new block …
=> feat: extract sBTC transactions in block observer

signer/src/block_observer.rs, signer/src/config.rs, signer/src/config/default.toml, signer/src/stacks/api.rs, signer/tests/integration/contracts.rs
Update code and config to support multiple stacks urls.
Closes: #225 
Config and stacks api now store multiple endpoints. Stacks api also keeps an index for the current endpoint. This index is incremented on network failure. 
Existing tests have been updated to check previous and new functionality.
=> Update signer to support multiple stacks node urls

Makefile, blocklist-client/src/main.rs, devenv/service-test/curl-test.sh, docker-compose.emily.yml, emily/handler/Cargo.toml, emily/handler/src/bin/emily-lambda.rs, emily/handler/src/bin/emily-server.rs, emily/handler/src/context.rs, emily/handler/src/database/accessors.rs, emily/handler/src/lib.rs, emily/handler/src/main.rs, emily/handler/tests/integration/accessors.rs, emily/handler/tests/integration/main.rs, emily/handler/tests/integration/util/constants.rs, emily/handler/tests/integration/util/mod.rs
Closes: #N/A
I added this change because iterating on the update command was taking too long with the 30 seconds of recompile and run time for emily running in a docker container with the apigateway wrapper. This change adds the ability to run emily as a warp service locally.
Note that this is required for https://github.com/stacks-network/sbtc/issues/360 because running the apigateway container locally won't be feasible for `arm64` chips once the `sbtc` library is imported. This isn't going to be an issue in production because it will only use `intel x86` processors for which this library is fine.
- Changes the Makefile to have slightly better commands
- Changes the emily docker compose to not always include the apigateway container
- Creates two binary files for the emily handler - one …
=> Emily as Local Warp Service

Cargo.lock, Makefile, devenv/service-test/curl-test.sh, emily/handler/Cargo.toml, emily/handler/src/api/routes/mod.rs, emily/handler/src/bin/emily-lambda.rs, emily/handler/src/bin/emily-server.rs, emily/handler/src/context.rs, emily/handler/tests/integration/util/constants.rs
Closes: #273
This ticket closes the local prefix issue by only adding the prefix on the lambda binary configuration with the `testing` feature. The `sam` cli that's used to run the lambda locally forcibly includes the `/local` prefix to prevent any accidental running of the `sam` development environment in the cloud, so the only way to get around this is to make adding the path conditional.
The `route` commands needed to change to return tuples of replies because the output of the filters needs to be a tuple in order to continue composing the filter with `and` warp filters - this is because it needs to be possible to convert the output into function arguments for the next filter to receive.
It's a bit wonky, but necessary.
Tested with integration tests and also on local make commands.
=> feat: Emily server cli args + remove "/local" path prefix

.generated-sources/emily/openapi/emily-openapi-spec.json, Cargo.lock, Makefile, devenv/service-test/curl-test.sh, emily/handler/Cargo.toml, emily/handler/src/api/handlers/deposit.rs, emily/handler/src/api/handlers/withdrawal.rs, emily/handler/src/api/models/common/mod.rs, emily/handler/src/api/models/deposit/requests.rs, emily/handler/src/api/models/withdrawal/requests.rs, emily/handler/src/api/routes/deposit.rs, emily/handler/src/api/routes/mod.rs, emily/handler/src/bin/emily-lambda.rs, emily/handler/src/bin/emily-server.rs, emily/handler/src/common/error.rs, emily/handler/src/context.rs, emily/handler/src/database/accessors.rs, emily/handler/src/database/entries/deposit.rs, emily/handler/src/database/entries/mod.rs, emily/handler/src/database/entries/withdrawal.rs, emily/handler/tests/integration/endpoints/deposit.rs, emily/handler/tests/integration/endpoints/withdrawal.rs, emily/handler/tests/integration/util/constants.rs, emily/handler/tests/integration/util/mod.rs
Partially closes: #348 
Finishes the put requests for the deposit and withdrawal entries.
The last steps handle are 
- Chainstate update with a reorg.
- Hidden conflicts.
This PR alters the deposit and withdrawal update structures and implements the update api calls for the deposits and withdrawals. 
- Makefile
- Adds two watch commands for emily api
- Deposit and Withdrawal
- Changed the update request structure to only include fields relevant to an update
- Added update functionality for deposit and withdrawal entries
Tested with new integration tests.
=> feat: Update requests for deposit and withdrawals

signer/migrations/0003__create_tables.sql, signer/src/block_observer.rs, signer/src/stacks/contracts.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/dummy.rs, signer/src/transaction_signer.rs, signer/src/wsts_state_machine.rs, signer/tests/integration/postgres.rs
Closes https://github.com/stacks-network/sbtc/issues/304.
This isn't really necessary. I just decided to working on something that requires less mental energy while in transit and this fit the bill.
* Allow `created_at` fields in all tables to be set automatically on insert with defaults
* Don't set the `created_at` fields when inserting data in the database.
* Remove the `created_at` fields from the model types.
* Don't update the `query!` and `query_as!` macro usage. I don't think this is worth the hassle.
I had to update one of the parameters in one of the tests since the test now fails due to randomness. Signers randomly reject requests and if enough of them reject the request than the test will fail. So I made sure that there were enough signers so that it was very unlikely by chance …
=> refactor: automatically set created_at columns

.generated-sources/emily/openapi/emily-openapi-spec.json, Makefile, emily/handler/src/api/handlers/deposit.rs, emily/handler/src/api/handlers/withdrawal.rs, emily/handler/src/api/models/withdrawal/requests.rs, emily/handler/tests/integration/complex/reorg.rs, emily/handler/tests/integration/endpoints/deposit.rs, emily/handler/tests/integration/endpoints/withdrawal.rs, emily/handler/tests/integration/populate/mod.rs
Closes: #N/A
Part of the implementation of the reorg handling.
Adds stacks block height correctly to operation handling.
Integration and unit tests.
=> feat: Add stacks block height to withdrawal request (reorg part 1/4)

Cargo.lock, Cargo.toml, signer/Cargo.toml, signer/src/api/mod.rs, signer/src/api/new_block.rs, signer/src/api/status.rs, signer/src/error.rs, signer/src/lib.rs, signer/src/main.rs, signer/src/stacks/contracts.rs, signer/src/stacks/mod.rs, signer/src/stacks/wallet.rs, signer/src/stacks/webhooks.rs, signer/tests/integration/postgres.rs
Closes https://github.com/stacks-network/sbtc/issues/441.
* Add concrete types for `POST /new_block` webhooks with types that match on smart contract events. There are a few other kinds of events by this PR only adds types for smart contract events.
* Set up a basic web server with two endpoints, one for the webhooks and another for the application status.
* Rename `Value` to `ClarityValue` where appropriate.
This includes a unit test that checks the deserialization of the webhooks emitted from stacks core. This payload was sent from a stacks core node under Nakamoto on commit https://github.com/stacks-network/stacks-core/commit/cbf0c52fb7a0b8ac55badadcf3773ca0848a25cf which was made on 2024-08-20. The testing setup here followed the same testing setup as in …
=> feat: add types for smart contract events

emily/handler/src/database/accessors.rs, emily/handler/src/database/entries/chainstate.rs, emily/handler/src/database/entries/deposit.rs, emily/handler/src/database/entries/mod.rs, emily/handler/src/database/entries/withdrawal.rs, emily/handler/tests/integration/accessors.rs, emily/handler/tests/integration/endpoints/withdrawal.rs, emily/handler/tests/integration/util/mod.rs
Closes: #N/A
Part of the reorg handling PR but broken up.
- Adds sort key ordered queries. 
- Adds specific functions for querying by last modified height for deposit and withdrawal entries.
- Additionally makes the output of the operation by status queries in sorted order by last modified height.
Integration and unit tests.
=> Sort key ordered dynamodb access (reorg part 3/4)

emily/handler/src/api/handlers/chainstate.rs, emily/handler/src/api/handlers/deposit.rs, emily/handler/src/api/handlers/internal.rs, emily/handler/src/api/handlers/mod.rs, emily/handler/src/api/handlers/withdrawal.rs, emily/handler/src/common/error.rs, emily/handler/src/database/accessors.rs, emily/handler/src/database/entries/chainstate.rs, emily/handler/src/database/entries/deposit.rs, emily/handler/src/database/entries/withdrawal.rs, emily/handler/tests/integration/accessors.rs, emily/handler/tests/integration/complex/reorg.rs
Closes: #348 
Handles reorgs when the chainstate updates.
Also adds a gate to other modifying API requests that prevents state alteration when the api is reorganizing. We can likely remove this gate long term but for now I'm adding it for stability.
Adds reorganization handling.
Tested with unit tests.
=> feat: Emily reorg handling. (reorg part 4/4)

contracts/contracts/sbtc-registry.clar, contracts/contracts/sbtc-withdrawal.clar, contracts/tests/clarigen-types.ts, contracts/tests/sbtc-deposit.test.ts, contracts/tests/sbtc-registry.test.ts, contracts/tests/sbtc-token.test.ts, contracts/tests/sbtc-withdrawal.test.ts
Closes https://github.com/stacks-network/sbtc/issues/449.
* Break up the `complete-withdrawal` function into two; one for accepts and another for rejects. Make all function arguments for both non-optional.
* Change the topics to match accept and reject.
This is a minor refactor to the last step of the withdrawal contract calls, but I added two more tests just to be extra sure that this is okay.
=> refactor: refine smart contract print events

signer/src/block_observer.rs, signer/src/error.rs, signer/src/stacks/api.rs
Closes: #434
Related to: #409 
This took a little longer than I thought as I was trying to get a node with the contracts running where I could see what's actually being output. I really wanted to do this without pulling more dependencies on `stacks-core`, but that turned out to take more time than I think it's worth for right now, so I ended up just using Clarity's own `Value` type for de/serialization so we can get this closed.
Adds an additional method to the Stacks API client for calling the `/v2/data_var` endpoint and retrieving the value of a contract `data-var`.
Added mocked tests. Mocked responses are generated by building up the Clarity type as a `Value`, serializing it and placing it into the API's response JSON format. I added test cases for both empty list and max-size (128).
=> add support for get-data-var stacks node api call

signer/src/config.rs, signer/src/error.rs, signer/src/stacks/contracts.rs, signer/src/stacks/events.rs, signer/src/stacks/mod.rs, signer/src/stacks/wallet.rs
Closes part of https://github.com/stacks-network/sbtc/issues/448. There is a small part left out of this PR, where I do not parse the recipient into a proper type. That will be done in a subsequent PR.
1. Add functions for deconstructing print event Clarity `Values` into regular types.
2. Be explicit about the endianness of the signer bitmap when converting it into an integer.
I did some local testing, but ran into an issue with my local stacks-node not confirming my contract call transaction after the first. Not sure what the issue is. When I get that sorted I think this can be considered "well-tested".
=> feat: transform print events into proper types

Cargo.lock, emily/handler/src/api/handlers/chainstate.rs, emily/handler/src/api/handlers/withdrawal.rs, signer/Cargo.toml, signer/src/blocklist_client.rs, signer/src/config.rs, signer/src/context.rs, signer/src/error.rs, signer/src/lib.rs, signer/src/main.rs
Closes: #467
Was looking into the wire-up of config, runloop, etc. with libp2p and thought I'd come with a boilerplate suggestion for the signer binary runtime since it's very basic atm.
- I removed the `LazyLock` static configuration in favor of a `SignerContext` object which can be passed down from `main` into subroutines (a better pattern, imo).
- Added application signalling (for ctrl+c, SIGHUP, SIGTERM, SIGINT) but can be expanded to other things like "ConfigReload" or whatever. This uses a broadcast channel which each component can subscribe to to receive shutdown events and shut itself down gracefully (if necessary).
EDIT: This might actually be a better option for communication between components, i.e. when a p2p message is received, or a p2p broadcast should be sent.
- Changed …
=> suggestion for signer runtime

Cargo.lock, Cargo.toml
Updates `sqlx` and `openssl` dependencies according to the [dependabot warnings](https://github.com/stacks-network/sbtc/security/dependabot).
Note that https://github.com/stacks-network/sbtc/security/dependabot/3 comes from `stacks-common` and `stackslib` which is still on `2.0.0`, so that would need to be updated upstream to fix.
Only changes to `Cargo.toml` and `Cargo.lock`
Standard build and test works the same.
=> chore: upgrade sqlx and openssl due to vulnerability warnings

contracts/contracts/sbtc-bootstrap-signers.clar, contracts/contracts/sbtc-registry.clar, contracts/docs/sbtc-bootstrap-signers.md, contracts/tests/clarigen-types.ts, contracts/tests/sbtc-bootstrap-signers.test.ts, contracts/tests/sbtc-registry.test.ts, signer/src/stacks/contracts.rs
Closes https://github.com/stacks-network/sbtc/issues/424
* Allow the signature threshold be changed during rotate-keys contract calls.
* Add new tests given the new behavior.
=> feat: modify signature threshold rotate keys

signer/migrations/0003__create_tables.sql, signer/src/api/mod.rs, signer/src/api/new_block.rs, signer/src/config.rs, signer/src/config/default.toml, signer/src/error.rs, signer/src/main.rs, signer/src/stacks/events.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/dummy.rs, signer/src/testing/mod.rs, signer/tests/fixtures/complete-deposit-event.json, signer/tests/fixtures/withdrawal-accept-event.json, signer/tests/fixtures/withdrawal-create-event.json, signer/tests/fixtures/withdrawal-reject-event.json, signer/tests/integration/contracts.rs, signer/tests/integration/postgres.rs
Closes https://github.com/stacks-network/sbtc/issues/426. This wraps up the handler for stacks print events.
* Add the network to the list of options in the signer's config file.
* Have the private key in the config file to be the generic signer private key.
* Add new tables for our print events from the `sbtc-registry` smart contract.
* Add functions for writing the above print events to the database.
* Add test fixtures for the various print events and unit tests that use them.
This includes a unit test that checks the deserialization of the webhooks emitted from stacks core. This payload was sent from a stacks core node under Nakamoto on commit https://github.com/stacks-network/stacks-core/commit/cbf0c52fb7a0b8ac55badadcf3773ca0848a25cf which was made on 2024-08-20. The raw body of the …
=> feat: add handler for smart contract events

signer/src/config.rs, signer/src/config/default.toml, signer/src/main.rs
Adds config support for the event observer. 
Adds a new configuration section under `signer`: `event_observer`, with two properties: `bind` and `port`.
```toml
#
[signer.event_observer]
bind = "0.0.0.0"
#
port = 8801
```
Added relevant asserts to the `load_default_config` test.
=> feat: add config for event observer

signer/src/config.rs, signer/src/config/default.toml, signer/src/testing/mod.rs
Adds support for configuring bitcoin RPC endpoints, both via config file and environment.
- Add support for bitcoin RPC endpoint configuration. This accepts a list, so we should do the same with the `BitcoinCoreClient` as was done with the `StacksClient` and support rotating endpoints on failure. This could be important if the signer wants to avoid any potential downtime during i.e. bitcoin core binary updates, etc.
- Added tests, and added a new convenience method on `Settings` for testing.
=> feat: add support for bitcoin core rpc endpoint configuration

contracts/contracts/sbtc-withdrawal.clar, contracts/tests/sbtc-withdrawal.test.ts, signer/src/bitcoin/utxo.rs, signer/tests/integration/rbf.rs, signer/tests/integration/utxo_construction.rs
Closes https://github.com/stacks-network/sbtc/issues/496 and closes https://github.com/stacks-network/sbtc/issues/503.
* Update the `initiate-withdrawal-request` public function to lock up the max-fee
* Update the `utxo` module to only adjust the signer's UTXO for fees. This means that we always send the amount in the withdrawal request to the intended recipient.
* There was a minor refactor of `UnsignedTransaction` where now unused functions were removed, and I moved the public function impls together.
On the clarity side, this adds a new test for the new behavior, just to be extra safe. On the signer side, the tests were updated after making the changes.
=> feat: change withdrawal lock amounts

signer/src/api/mod.rs, signer/src/api/new_block.rs, signer/src/config.rs, signer/src/config/default.toml, signer/src/lib.rs, signer/src/stacks/webhooks.rs
Closes https://github.com/stacks-network/sbtc/issues/501.
* Filter `new_block` webhook events on the `sbtc-registry` contract address.
* Add the sbtc contract deployer to the signer's config. Check that the network embedded in the address matches the network set in the config.
I'm not 100% happy with adding the deployer address to the config, since it's not _really_ a configuration option. We do not expect signer operators to set this once the contracts have been deployed. While we develop the application we kinda need the option to change it so it makes sense to have this configurable, which is why I added it. I'm open to suggestions though.
The existing webhook tests need the value that is added to the config in order to function correctly (the address in the fixture needs to match the …
=> feat: check contract origin webhook handler

sbtc/src/deposits.rs, signer/src/bitcoin/utxo.rs
Closes https://github.com/stacks-network/sbtc/issues/514
* Use the regenerated deposit and reclaim scripts when passing on the validated deposit info.
There isn't really a new test for this change, since it involves constructing a collision in a merkle tree. So if the existing tests pass then we should be good.
=> fix: pass on validatated script when validating deposit scripts

devenv/local/docker-compose/docker-compose.yml, docker-compose.test.yml, signer/src/bitcoin/utxo.rs, signer/src/config/default.toml, signer/src/config/error.rs, signer/src/config/mod.rs, signer/src/config/serialization.rs, signer/src/main.rs, signer/src/testing/storage.rs
I'm breaking up a larger branch from yesterday re: running the signer, so I decided to clump together the "config-related" changes here that I had made (hope that's okay for this one to save a little time, otherwise I'll need to go back and un-refactor,  apply the changes separately then re-refactor -- the followup PR's are more isolated):
Closes: 
- #520 
- #513 
I added PR comments to make it clear what is what.
Also restructured the `config` module a little as it was starting to feel a little messy/unwieldy.
- Restructured the `config` module for better code isolation.
- Removed the `stacks.api` config stanza as I don't see that it's used anywhere.
- Added a little more documentation in `default.toml`
- Added support for db endpoint configuration (#520) via the `db_endpoint` property. …
=> feat: config cleanup + db config + url parsing error

sbtc/src/testing/regtest.rs, signer/migrations/0003__create_tables.sql, signer/src/bitcoin/utxo.rs, signer/src/block_observer.rs, signer/src/error.rs, signer/src/message.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/storage/sqlx.rs, signer/src/testing/dummy.rs, signer/src/testing/storage/model.rs, signer/src/testing/transaction_signer.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs, signer/tests/integration/postgres.rs, signer/tests/integration/rbf.rs, signer/tests/integration/utxo_construction.rs
Closes https://github.com/stacks-network/sbtc/issues/527.
* Update 'recipient' column names and their type to expect a `bytea` for a `ScriptPubKey`. This makes it more consistent with the code base, as well as reduces overall complexity (using an address is incorrect).
* Use `WithdrawalX` instead of `WithdrawX` for table, function, and struct names.
* Add the transaction ID to the `withdrawal_request` and `withdrawal_signer` tables.
* Add an internal `ScriptPubKey` type for interacting with the database.
This is a refactor, so if tests pass then we're good.
=> refactor: use the `ScriptPubKey` as recipient

signer/src/bitcoin/mod.rs, signer/src/block_observer.rs, signer/src/error.rs, signer/src/network/grpc_relay.rs, signer/src/network/in_memory.rs, signer/src/network/mod.rs, signer/src/stacks/api.rs, signer/src/stacks/contracts.rs, signer/src/stacks/wallet.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/postgres.rs, signer/src/testing/transaction_coordinator.rs, signer/src/testing/transaction_signer.rs, signer/src/testing/wallet.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs, signer/src/wsts_state_machine.rs, signer/tests/integration/postgres.rs
Implements part of the work done in https://github.com/stacks-network/sbtc/pull/507.
* Remove the associated error type from the `DbRead`, `DbWrite`, `BitcoinInteract`, and `MessageTransfer` traits.
* Fixes bug/typo in the tests that may have caused tests in `main` to fail.
This is just a refactor, so if the tests pass then all should be well.
=> refactor: remove associated error types from internal traits

sbtc/src/deposits.rs, sbtc/src/error.rs, sbtc/src/testing/regtest.rs, sbtc/tests/integration/validation.rs
Closes https://github.com/stacks-network/sbtc/issues/516 and addresses an issue pointed out in https://github.com/stacks-network/sbtc/issues/514#issuecomment-2350054724.
* Reject deposits where the reclaim script uses a lock-time that would disable the OP_CSV opcode. I'm still in disbelief at the design of that opcode, so I wouldn't be surprised if my understanding is just plain wrong.
* Fix an issue where `DepositScriptInputs::parse(script).deposit_script() != script`. Although it is very unlikely that this issue would sneak past validation, it could be problematic in other scenarios. Also, the intent is that `DepositScriptInputs::parse(script).deposit_script() == script` so let's make it so.
I'd like to add an integration test and I may still do so, but what is here is good enough for …
=> feat: reject non-standard deposit scripts and problematic lock-times

README.md, signer/src/storage/postgres.rs
Remove duplicated logic for `get_stacks_chain_tip`.
Existing tests pass (`cargo nextest r && make integration-test-full`).
=> Chore: remove duplicated get_stacks_chain_tip

sbtc/tests/integration/validation.rs, signer/src/bitcoin/utxo.rs, signer/src/testing/mod.rs, signer/tests/integration/utxo_construction.rs
Closes nothing.
This is a quick follow-up to https://github.com/stacks-network/sbtc/pull/535.
* Adds an integration test that checks the minimal-push-rule (to show that https://github.com/stacks-network/sbtc/pull/535 was necessary).
* Update some of our integration tests helper functions to go through the types in the `sbtc` crate.
This is a refactor that uses more internal types in the integration tests. The idea is that transactions that conform to the internal types will be accepted by bitcoin-core and make things work smoothly.
=> ci: more integration tests

signer/src/context/messaging.rs, signer/src/context/mod.rs, signer/src/context/termination.rs, signer/src/network/libp2p/event_loop.rs, signer/src/network/mod.rs
The `context.rs` was starting to get a little big, so I split it up a little bit to help keep code cohesion high. This was a pretty isolated change from one of my local branches and should help reduce conflicts from coming PRs.
No real functional changes, just organizational and convenience:
- Moves `context.rs` into `context/mod.rs` and refactors out messaging and termination types into `context/messaging.rs` and `context/termination.rs`.
- Consolidates the `P2P` events under a new variant.
- Adds a few `From<>`s on message variants to make it easier to read/write commands/events.
Nothing special, everything as before.
=> refactor: move context into its own dir and related updates

signer/src/api/new_block.rs, signer/src/bitcoin/client.rs, signer/src/bitcoin/mod.rs, signer/src/bitcoin/rpc.rs, signer/src/block_observer.rs, signer/src/context/mod.rs, signer/src/error.rs, signer/src/main.rs, signer/src/network/libp2p/swarm.rs, signer/src/network/mod.rs, signer/src/stacks/api.rs, signer/src/stacks/contracts.rs, signer/src/stacks/wallet.rs, signer/src/storage/model.rs, signer/src/testing/api_clients.rs, signer/src/testing/mod.rs, signer/src/testing/wallet.rs, signer/src/transaction_signer.rs, signer/src/util.rs, signer/tests/integration/bitcoin_client.rs, signer/tests/integration/bitcoin_rpc.rs, signer/tests/integration/complete_deposit.rs, signer/tests/integration/postgres.rs, signer/tests/integration/withdrawal_accept.rs
Addresses part of https://github.com/stacks-network/sbtc/issues/175 sorta, and paves the way for https://github.com/stacks-network/sbtc/issues/552.
While working on https://github.com/stacks-network/sbtc/issues/552, I realized that I needed to make quite a few auxiliary changes, so I stopped when it felt like a lot and decided to open this PR.
* Have the `AsContractCall::validate` function take something that implements the `Context` trait. This is needed for https://github.com/stacks-network/sbtc/issues/552.
* Allow for the inner context type to be exposed in tests.
* Make sure the `BitcoinCoreClient` and `StacksClient` implement Clone. This is preparation for changes to the `SignerContext` type, and allows for a simplification of the `InnerSignerContext` object.
* Implement …
=> refactor: setup bitcoin client use in validation

signer/src/block_observer.rs, signer/src/config/default.toml, signer/src/config/mod.rs, signer/src/context/messaging.rs, signer/src/context/mod.rs, signer/src/main.rs, signer/src/testing/mod.rs
Closes: #548 
- Adds the block observer to the main entry-point
- Changes the block observer db-update notification to use the app signalling channel (and updated tests)
- Removes `Storage` from the `BlockObserver` and adds `Context` (storage is retrieved from the context)
- Fixed an issue in block observer tests where the test harness returned a stream of non-result items
- Added configuration for bitcoin zmq block hash stream endpoints
- Updated the run-loop for the block observer
TODO: Add validation for block stream config
Same test suite as before.
=> feat: run block observer

Cargo.lock, Cargo.toml
There is a DoS vulnerability in `wsts` `9.1.0` and earlier.  This change updates `sbtc` to use the newly published `9.2.0` crate which fixes the vulnerability.
Closes: #?
- [ x] I have performed a self-review of my code
- [ x] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules
=> Update wsts dependency to 9.2.0

signer/src/block_observer.rs, signer/src/storage/postgres.rs, signer/src/testing/wallet.rs, signer/tests/integration/contracts.rs, signer/tests/integration/postgres.rs
Closes https://github.com/stacks-network/sbtc/issues/523.
* This change makes sure that we only extract stacks transactions that were deployed by the appropriate entity.
There was a test for extracting relevant stacks transactions and it was updated to check that contract calls to smart contracts with the incorrect stacks addresses are ignored.
=> feat: db stacks transactions validated incorrectly

signer/src/bitcoin/mod.rs, signer/src/block_observer.rs, signer/src/context/mod.rs, signer/src/main.rs, signer/src/testing/api_clients.rs, signer/src/testing/context.rs, signer/src/testing/mod.rs
Closes https://github.com/stacks-network/sbtc/issues/597.
* Move the stacks client into the signer context
* Make sure the async trait functions implement `Send`
Moreover nothing uses the new context for the stacks client so all tests should pass.
=> feat: move stacks client into signer context

signer/src/block_observer.rs, signer/src/context/mod.rs, signer/src/emily_client.rs, signer/src/main.rs, signer/src/testing/context.rs, signer/src/testing/transaction_coordinator.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/complete_deposit.rs, signer/tests/integration/postgres.rs, signer/tests/integration/withdrawal_accept.rs
Add Emily client to context
Usual boilerplate, based on https://github.com/stacks-network/sbtc/pull/606
=> feat: add emily to context

signer/src/message.rs, signer/src/storage/postgres.rs, signer/src/testing/message.rs, signer/src/testing/transaction_signer.rs, signer/src/testing/wallet.rs, signer/src/transaction_signer.rs
The transaction signer wasn't broadcasting its withdrawal decision in `handle_pending_withdraw_request()`; this PR adds it and adjusts both the deposit + withdrawal tests to verify that it's broadcasted.
- Broadcasts a `SignerWithdrawalDecision` in `handle_pending_withdrawal_request()`.
- Adds asserts to both deposit and withdrawal tests to ensure that this is done for both.
- Some renames of `withdraw` to `withdrawal`
Nothing special other than what's noted above.
=> feat: broadcast withdrawal decision + tests

.generated-sources/emily/openapi/emily-openapi-spec.json, Makefile, devenv/aws-setup/initialize.py, emily/cdk/lib/emily-stack-utils.ts, emily/cdk/lib/emily-stack.ts, emily/handler/src/api/handlers/deposit.rs, emily/handler/src/api/models/deposit/mod.rs, emily/handler/src/api/models/deposit/requests.rs, emily/handler/src/database/entries/deposit.rs, emily/handler/tests/integration/complex/reorg.rs, emily/handler/tests/integration/endpoints/deposit.rs, emily/handler/tests/integration/populate/mod.rs, emily/handler/tests/integration/util/mod.rs
Closes: #595 
1. Adds a feature to the Emily API CDK template where the AWS resources can be created without the ApiGateway and the Emily Lambda when an environment variable is set. This is useful for testing when the Emily lambda handler isn't going to be fielding the API requests
2. Adds `deposit_script` and `reclaim_script` to the Emily API `Deposit` and `DepositInfo` resources and updates tests accordingly.
Tested with integration tests. At the moment this requires three separate commands to run concurrently, and is easiest with three terminals. 
- Terminal 1: `make emily-integration-env-up`
- Terminal 2: `make emily-server-watch`
- Terminal 3: `make emily-integration-test`
> Note: We *won't* be fixing this need for three terminals for integration tests soon so we can focus solely on …
=> 595 feature provide raw transaction data for emily api deposit operations

signer/src/context/messaging.rs, signer/src/testing/transaction_coordinator.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs
Closes: #588
This adds a new `TxSignerEvent` variant `NewRequestsHandled`, which is emitted at the end of the tx-signer's `handle_new_requests()` successful completion and used as the trigger for the transaction coordinator. So the new flow is:
Block Observer: `BitcoinBlockObserved` -> Transaction Signer: `NewRequestsHandled` -> Transaction Coordinator runs
Coordinator tests have been updated to use this new trigger.
=> feat: fix race condition described in #588

emily/handler/src/database/entries/deposit.rs, emily/handler/src/database/entries/mod.rs, emily/handler/src/database/entries/withdrawal.rs, emily/handler/tests/integration/endpoints/deposit.rs, emily/handler/tests/integration/endpoints/withdrawal.rs, signer/src/transaction_coordinator.rs
Make fulfilment required for confirmed requests instead of accepted ones.
Emily integrations tests are green.
=> Change mandatory fulfillment for confirmed instead of accepted requests

signer/src/block_observer.rs, signer/src/storage/in_memory.rs
Closes: https://github.com/stacks-network/sbtc/issues/625
In `extract_deposit_requests`, we store the bitcoin tx for deposit requests (both the bitcoin tx and the "raw" `TransactionType::DepositRequest` tx).
Also added the `write_transaction` call in `write_bitcoin_transactions` and `write_stacks_transactions` for in memory storage impl, as done by the pg one.
Added a check on an existing test, and tested on the integration test in https://github.com/stacks-network/sbtc/pull/609.
=> Store deposit requests txs when extracted

signer/src/block_observer.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs
Removes error propagation in the block observer, transaction signer & coordinator event loops, logging the error and waiting for the next run (as these errors can be temporary) instead of causing the signer to shutdown.
This is primarily a problem when bootstrapping because DKG hasn't yet been run, and then we hit an error regarding this and the signer immediately shuts down (which in turn makes it impossible to run DKG).
As described in description; error propagation for these event loops are largely removed (we may want to match on some specific truly-fatal errors later, but now it will just keep retrying).
Nothing special, has been run against devenv.
=> feat: make block observer + signer + coordinator more robust

signer/src/block_observer.rs, signer/src/error.rs, signer/src/keys.rs, signer/src/main.rs, signer/src/stacks/api.rs, signer/src/stacks/contracts.rs, signer/src/stacks/wallet.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/dummy.rs, signer/src/testing/transaction_coordinator.rs, signer/src/testing/transaction_signer.rs, signer/src/testing/wallet.rs, signer/src/testing/wsts.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs, signer/src/wsts_state_machine.rs, signer/tests/integration/contracts.rs, signer/tests/integration/postgres.rs
Closes https://github.com/stacks-network/sbtc/issues/563.
* Remove some of the unnecessary fields from the `TxSignerEventLoop` and `TxCoordinatorEventLoop`. We can remove the private key field too but it's better to move that into the wallet so I left it as is for now.
* Removed an unnecessary input from the `RotateKeysV1` transaction object.
* Added a method for loading the `SignerWallet` from the database.
* Added trait functions for fetching "fulfilled" requests from the database, partly implement one of these functions for the postgres type.
There is still some outstanding work here:
* ~Rename the `Fulfilled*Request` structs (the requests are only partly fulfilled). Name suggestions are welcome.~ Done.
* ~Fix-up the documentation on the `Fulfilled*Request` structs.~ Done.
* Add an …
=> feat: create `complete-deposit` sign requests

emily/handler/src/bin/emily-server.rs, emily/handler/src/context.rs, sbtc/Cargo.toml, sbtc/src/deposits.rs, sbtc/src/lib.rs, signer/src/transaction_coordinator.rs
There were a couple of things I noticed needed a spit-shine:
1. Tests from the crate don't run from VS Code. This is a "bug" that wasn't caught in CI because CI probably compiles tests with all features enabled by default, while not all features are enabled when running tests in my IDE.
2. We do not expose the `lock_time` and the `user-supplied-lock-script` from the reclaim script. The changes here are to help out with some of the work in https://github.com/stacks-network/sbtc/pull/635.
1. Make sure the necessary dependencies were added as dev dependencies.
2. Expose the lock time and the user supplied lock script from in the reclaim script.
I'm torn on whether I should add getters and such for `DepositInfo`, since it is supposed to represent a correctly parsed deposit request, and thus …
=> refactor: small fixes comment updates

emily/handler/src/bin/emily-server.rs, emily/handler/src/context.rs, signer/src/block_observer.rs, signer/src/testing/block_observer.rs, signer/src/testing/mod.rs, signer/src/transaction_coordinator.rs
Writing some block observer tests and the file was getting a bit long, so I refactored out the test harness etc. to a separate file in `testing` like we do for the signer & coordinator.
Pulling this into a separate PR to make review easy.
95% organizational, the rest is just cargo fmt + clippy + some getters on the test harness since now the fields aren't directly accessible from tests in the "real" block observer file.
Nothing special, everything is as before.
=> chore: move block observer testing stuff around

devenv/local/docker-compose/Dockerfile.emily, devenv/local/docker-compose/Dockerfile.sbtc-bridge-website, devenv/local/docker-compose/docker-compose.yml
Closes: #638 
1. Adds `sbtc` bridge website container to docker compose.
2. Fixes a bug I introduced where main isn't used when compiling the `emily` sources.
Tested by running the following:
- `docker compose --file devenv/local/docker-compose/docker-compose.yml --progress=plain up sbtc-bridge-website`
=> 638 chore add bridge website docker container to devenv

Dockerfile, README.md, flake.lock, flake.nix
As someone who was configuring how to build this project for the first time, I thought it would be useful to have an easy way to install all build dependencies at once. I gave this a shot with `nix`. 
The result is that if you have `nix` installed and configured, you can run `nix develop` to enter a shell having all dependencies installed. Well, all except Smithy, who doesn't have a nix package yet.
Closes: ~NA~
- Add `flake.nix` for development shells.
- Install [`nix`](https://determinate.systems/posts/determinate-nix-installer/)
- Make sure you have flakes enabled (the installer linked above takes care of it, else see [here](https://nixos.wiki/wiki/Flakes))
- Run `nix develop`
=> chore: add `flake.nix` including developer shell

README.md
This PR consolidates the Google Docs scattered across multiple issues into a single Google Drive folder, linked in the README.
=> chore: add Google Drive folder to README

signer/src/context/messaging.rs, signer/src/stacks/wallet.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/transaction_coordinator.rs
Fixes an issue that we were seeing on main.
* Add a method to retrieve the number of signatures received by a transaction locked with a multi-sig "script" on Stacks.
* Add a consolidated receive function to the transaction coordinator object.
=> fix: add a consolidated receiver

signer/src/network/libp2p/swarm.rs
Enables disjoint path lookups for libp2p's Kademlia implementation (part of S/Kademlia). This is a mitigation against byzantine peers attempting confuse the network by altering data on lookups crossing their path.
This change makes nodes query multiple disjoint paths (i.e. starting at different peer nodes) concurrently and requiring a minimum allowable quorum on the result.
More information:
- https://www.researchgate.net/publication/4319659_SKademlia_A_practicable_approach_towards_secure_key-based_routing
- https://github.com/libp2p/rust-libp2p/pull/1473
Enables disjoint path lookups in the Kademlia configuration for the libp2p swarm.
=> feat: enable disjoint queries for kademlia

signer/src/block_observer.rs, signer/src/error.rs, signer/src/main.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/emily.rs, signer/tests/integration/main.rs, signer/tests/integration/setup.rs, signer/tests/integration/zmq.rs
Closes https://github.com/stacks-network/sbtc/issues/522.
This was largely fixed in https://github.com/stacks-network/sbtc/pull/675.
* Have the `load_latest_deposit_requests` function fetch and store all validated deposits that have been confirmed.
* Remove unnecessary fields from the `BlockObserver`.
* Load data from Emily after processing the block.
The tests were modified after two functions were essentially merged.
=> feat: block observer processes confirmed deposit requests

emily/handler/src/api/handlers/chainstate.rs, emily/handler/src/api/handlers/deposit.rs, emily/handler/src/api/handlers/withdrawal.rs, emily/handler/src/database/entries/deposit.rs, emily/handler/src/database/entries/withdrawal.rs, emily/handler/tests/integration/deposit.rs, emily/handler/tests/integration/withdrawal.rs
Changes Emily to accept deposit / withdrawal updates that have unknown chainstate entries, and updates the chainstate
entries to match the chainstates that can be inferred from the deposit / withdrawal updates.
Closes: #?
- Deposit update flow will update chainstate
- Withdrawal update flow will update chainstate
Tested with integration tests.
=> Feat/Emily can populate chainstate table with the height and hash inferred from deposit and withdrawal updates.

.github/actions/dockerfiles/Dockerfile.signer.debian, .github/workflows/image-build.yaml
Closes: #693 
This PR adds a docker container publishing CI action that will build release a docker container for the signer. It uses a similar workflow to the one used in `stacks-core`, but it appears that the one in stacks-core has never been run. This workflow step can only be run manually with a release tag that corresponds to a release branch. This is to avoid accidentally releasing the wrong thing.
This means to release docker images for version `a.b.c` you'll need to do the following:
1. Push to the branch `release/a.b.c`
1. Go to workflows and manually trigger this workflow with the following info:
1.  `tag = a.b.c`
1. `push-image = true`
1. and then if you want the latest tag to be this version, you'd do `is-latest = true`
- Creates a GitHub workflow to release the sbtc signer.
- …
=> Add Docker Container Release Workflow

.github/workflows/image-build.yaml
Fixes bug.
I forgot to remove the `input` variables when I switched to making it trigger on a tag update.
=> fix: have docker build always push the image

.generated-sources/emily/openapi/emily-openapi-spec.json, emily/handler/src/api/handlers/deposit.rs, emily/handler/src/api/models/deposit/mod.rs, emily/handler/src/database/entries/deposit.rs, emily/handler/tests/integration/deposit.rs, sbtc/src/deposits.rs, sbtc/src/error.rs, sbtc/src/testing/deposits.rs, sbtc/tests/integration/validation.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/dummy.rs
Closes https://github.com/stacks-network/sbtc/issues/516, with proper lock-time handling being done when https://github.com/stacks-network/sbtc/issues/380 gets closed.
After this change, locktimes used as `OP_CSV` inputs in the reclaim script only use the 16 least significant bits for the value of the locktime. All other bits in the 32-bit locktime must be zero or else the deposit transaction will fail validation. When we support time-based locktimes, a user may set bit (1 << 22) to indicate that the locktime value is time based, as described in BIP-68.
* Use rust-bitcoin's relative `LockTime` type for representing the lock-time under the hood.
* Reject time-based `locktime`s. We've set ourselves up to support them, but the real work lies in the signer.
* Change the underlying type for a …
=> feat: properly parse the reclaim script lock time

Makefile, README.md, devenv/hooks/pre-commit-make-lint.sh
Add _optional_ Git hooks for those who don't like to push code only to find it rejected by the CI linter.
Read the new `README.md` section. After installing the hooks, try making a modification that `cargo fmt` won't like. Try to commit it, or try running `.git/hooks/pre-commit-make-lint.sh`.
=> feat: add optional git hooks

.generated-sources/blocklist-api/Cargo.toml, Cargo.lock, signer/src/network/libp2p/event_loop.rs
This resolves part of #669 and is otherwise just pulling in the **unreviewed** libp2p-related changes that were already made in `feat/demo-cli` into main.
This changes how the libp2p swarm is polled, ensuring that it is done at a constant interval "driving it" and also ensuring that `tokio::select!` can't abort a p2p publish or the processing of an incoming message if those two events occur at the same time.
In short, what can happen (before this change) is that if both a network message is received (via the `swarm.select_next_some()`) AND a publish command is being processed (via the `signal_rx.recv()`), then these two will race to finish. When one of them finishes, `tokio::select!` will abort the competing tasks which can result in either a message not being published to the network or …
=> feat: import libp2p changes from `feat/demo-cli` (related to #669)

signer/src/stacks/contracts.rs
Closes https://github.com/stacks-network/sbtc/issues/734.
* Update the `complete-deposit-wrapper` and `accept-withdrawal-request` contract call with the new parameter.
This is untested (I'm running it now to make sure the stacks-node accepts it). There will be quite some setup to do to properly test this, so I created https://github.com/stacks-network/sbtc/issues/735 for that work.
=> feat: update contract calls with burn block check inputs

signer/src/network/libp2p/event_loop.rs, signer/tests/integration/emily.rs
Small leftover from https://github.com/stacks-network/sbtc/issues/559
Fix Emily integration test and remove `ignore` guard now that Emily run in the integration test compose. Also sneaked in a small typo fix.
Test runs and passes.
=> chore: update emily integration test

signer/src/stacks/api.rs, signer/src/storage/model.rs
This was discovered during local testing
* Transform stacks blocks to bitcoin block hashes correctly.
* Don't retry on failure for `get_contract_source`.
I couldn't get the `link_blocks` integration test to pass locally, not sure what the issue was. @matteojug was able to get his local main version to pass though.
=> fix: local fixes linking stacks blocks to bitcoin blocks

signer/src/main.rs, signer/src/transaction_coordinator.rs
Followup for https://github.com/stacks-network/sbtc/issues/688
Reuse the same wallet object when deploying the different contracts to avoid conflicting nonces in mempool.
Also bump the block observer horizon to a reasonable value.
Tested on devenv: all the contracts were deployed in the same stacks block.
=> fix: reuse wallet when deploying contracts

contracts/contracts/sbtc-deposit.clar, contracts/contracts/sbtc-withdrawal.clar, contracts/tests/sbtc-deposit.test.ts, contracts/tests/sbtc-token.test.ts, contracts/tests/sbtc-withdrawal.test.ts
Closes https://github.com/stacks-network/sbtc/issues/779.
* Use `get-burn-block-info?` instead of `get-tenure-info?`.
* Update all of our tests, add one more.
I tested this locally in our local devnet and things worked as expected.
=> fix: update burn hash check in contract calls

signer/src/block_observer.rs, signer/src/context/termination.rs, signer/src/testing/context.rs
Partially resolves: #669 
Removes the `tokio::select!` from the block observer runloop which will ensure that if the signer receives a shutdown signal (other than `-9`) that it will complete its current run, writing any data, before shutting down.
- Added a new method on the `TestContext` for waiting for a specific `SignerSignal` and use it in the one test that needs to wait for `BitcoinBlockObserved`.
- Refactored the other tests there to use `TestContext`... just because (consistency?).
=> feat: refactor block observer runloop

signer/src/context/termination.rs, signer/src/transaction_coordinator.rs
Partially closes: #669
Removes the tokio::select! from the transaction coordinator runloop which will ensure that if the signer receives a shutdown signal (other than -9) that it will complete its current run, writing any data, before shutting down.
Nothing special, all tests pass
=> feat: refactor tx-coordinator runloop

signer/src/block_observer.rs, signer/src/error.rs, signer/src/stacks/api.rs, signer/src/testing/block_observer.rs, signer/src/testing/context.rs, signer/src/testing/mod.rs, signer/src/testing/stacks.rs, signer/tests/fixtures/stacksapi-v3-sortitions.json, signer/tests/integration/block_observer.rs, signer/tests/integration/contracts.rs, signer/tests/integration/emily.rs, signer/tests/integration/transaction_coordinator.rs
Closes https://github.com/stacks-network/sbtc/issues/778 and addresses part of https://github.com/stacks-network/sbtc/issues/685. 
* Change the `get_tenure` return type to include the anchor block hash and anchor block height.
* Make sure `fetch_unknown_ancestors` stops at the nakamoto start height.
I haven't updated the tests, so this will fail.
=> fix: stop at nakamoto block height

contracts/contracts/sbtc-deposit.clar, contracts/contracts/sbtc-registry.clar, contracts/contracts/sbtc-withdrawal.clar, contracts/tests/clarigen-types.ts, contracts/tests/sbtc-deposit.test.ts, contracts/tests/sbtc-token.test.ts, contracts/tests/sbtc-withdrawal.test.ts
This PR adds a 'sweep-txid' parameter to both 'completed-deposits' & 'accepted-withdrawals' that is then emitted from the registry contract, if successful. 
Closes: #583 
This contains an update to the withdrawal contract, deposit contract, registry contract, & corresponding test files.
This is successfully tested by extending existing unit tests that already cover emitted events.
=> Clarity/Sweep TXID

signer/src/stacks/contracts.rs
Followup for https://github.com/stacks-network/sbtc/issues/583
Add missing `sweep_txid` arg to complete deposit contract call.
I didn't fix `accept-withdrawal-request` since the error is probably more eloquent than using a `None` when we will need to address withdrawals; also, what should we put in there? Isn't it the same as `bitcoin-txid`?
Tested in devenv with demo script.
=> Add missing parameter to complete deposit call

emily/handler/src/api/handlers/deposit.rs, emily/handler/src/api/handlers/withdrawal.rs, emily/handler/src/database/accessors.rs, emily/handler/src/database/entries/deposit.rs, emily/handler/src/database/entries/withdrawal.rs, signer/src/api/new_block.rs, signer/tests/integration/stacks_events_observer.rs
Closes: #752
Adds retry on version conflict when updating an entry in a  dynamodb table to Emily. Also adds a function that prevents attempting an update when the entry doesn't need to consume the update.
Additionally, I had to change the order of the concurrent API calls updating Emily; it cannot receive updates to withdrawals that it doesn't know about yet, so the chainstate and create withdrawal calls need to occur first.
Tested with unit tests and integration tests.
=> feat: Retry updates when a version conflict fails update

signer/src/stacks/api.rs, signer/src/stacks/contracts.rs, signer/src/testing/block_observer.rs, signer/src/testing/context.rs, signer/src/testing/transaction_coordinator.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/contracts.rs, signer/tests/integration/emily.rs, signer/tests/integration/postgres.rs, signer/tests/integration/transaction_coordinator.rs
First part of: https://github.com/stacks-network/sbtc/issues/653
The second part is related to emily sidecar picking up the event and populating `rotate_keys_transactions` table; ~currently the coordinator keeps broadcasting rotate keys tx (that fails, after the first one) because it doesn't find any rotation in db~ (changed implementation, no longer true).
Submit rotate key if the latest DKG differs from chain registry data.
Tested in devenv and changed an integration test to check for the tx.
=> Submit rotate-key tx

signer/src/api/new_block.rs, signer/src/stacks/events.rs, signer/tests/fixtures/rotate-keys-event.json
Closes: #797 
- Add parsing of `rotate-keys` print envents in the `new_block_handler`
- Write the rotate-keys tx to the db
- Add `KeyRotation` to `RegistryEvent`
- Add `KeyRotationEvent` struct
- Add event parsing logic
- add unit tests
=> add parsing and handling of rotate-keys events

.generated-sources/blocklist-api/Cargo.toml, Cargo.lock, protobufs/stacks/signer/v1/decisions.proto, signer/src/error.rs, signer/src/keys.rs, signer/src/proto/convert.rs, signer/src/proto/generated/stacks.signer.v1.rs, signer/src/proto/mod.rs
This is more work on the path to https://github.com/stacks-network/sbtc/issues/412, and follows https://github.com/stacks-network/sbtc/pull/558, https://github.com/stacks-network/sbtc/pull/577, https://github.com/stacks-network/sbtc/pull/579, and https://github.com/stacks-network/sbtc/pull/727.
* Add conversion implementations between some of the protobuf types and their sister types.
This PR adds unit tests for all 13 conversion implementations.
=> feat: add protobuf conversion impls

signer/migrations/0003__create_tables.sql, signer/src/api/new_block.rs, signer/src/stacks/events.rs, signer/src/stacks/wallet.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/dummy.rs, signer/src/testing/wsts.rs, signer/tests/fixtures/completed-deposit-event.json, signer/tests/fixtures/withdrawal-accept-event.json, signer/tests/integration/postgres.rs
Closes: #801, #726
- Extended the CompletedDepositEvent, WithdrawalAcceptEvent, and KeyRotationEvent structs to contain the missing data
- Extended the corresponding events parsing methods in `RawTupleData`
- Extended the DB migrations to contain the new data
- Extended the `completed_deposit_event`, `write_withdrawal_accept_event`, and `write_rotate_keys_transaction` to save the new data.
- Set the `DepositUpdate` and `WithdrawalUpdate` in `handle_withdrawal_accept` and `handle_completed_deposit` with the real block values from the event, replacing the old dummy ones.
- 
- add new unit and integration tests, and adapt old ones.
=> feat: 801 feature extend db schemas to save all data from new block print events

signer/Cargo.toml, signer/src/bin/demo_cli.rs, signers.sh
Add `demo-cli` tool used during demo.
Includes `demo-cli` binary originally from https://github.com/stacks-network/sbtc/pull/649 (with some small changes). We can use `./signers.sh demo` to issue a donation and create a deposit request, and `./signers.sh info` to get signers related info to be used to configure the bridge.
Tested on devenv.
=> chore: demo-cli

README.md
Fixes outdated path referencing docker-compose file
=> chore: dead link in readme

.generated-sources/emily/openapi/build.rs, .generated-sources/emily/openapi/emily-openapi-spec.json, emily/handler/src/api/handlers/chainstate.rs, emily/handler/src/api/handlers/deposit.rs, emily/handler/src/api/handlers/health.rs, emily/handler/src/api/handlers/testing.rs, emily/handler/src/api/handlers/withdrawal.rs
Closes: #814 
Adds api key level security to private Emily API endpoints.
- Adds openapi template builder modifiers so the API keys can be added
- Adds the security requirement to the API endpoints 
- Tested with integration tests and building.
=> 814 feature add api key security to private endpoints on emily openapi spec

signer/src/error.rs, signer/src/testing/transaction_signer.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs
`sBTC` messages contain a signature and a public key, in addition to the payload.  Verifying the message shows that it has not been tampered with.
`WSTS` message payloads either contain a `signer_id`, or are coordinator messages.  So in addition to verifying the signature, we also need to show that the public key used to sign was the correct public key for that signer (or the coordinator).
Closes: #578 
Call `verify` on the `sBTC` message, then check that the message was signed by the correct public key.
All unit and integration tests still pass.
- [ x] I have performed a self-review of my code
- [ x] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules
=> check that wsts messages are signed by the specified signer_id

protobufs/stacks/signer/v1/decisions.proto, signer/migrations/0003__create_tables.sql, signer/src/bitcoin/validation.rs, signer/src/message.rs, signer/src/proto/convert.rs, signer/src/proto/generated/stacks.signer.v1.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/message.rs, signer/src/testing/storage/model.rs, signer/src/testing/transaction_signer.rs, signer/src/transaction_signer.rs, signer/tests/integration/emily.rs, signer/tests/integration/postgres.rs, signer/tests/integration/setup.rs, signer/tests/integration/transaction_signer.rs
Closes https://github.com/stacks-network/sbtc/issues/839, which is a small part of https://github.com/stacks-network/sbtc/issues/798.
* Rename the `is_accepted` to `can_accept`, to note whether the deposit was blocked by the blocklist client.
* Always use the blocklist client for each deposit request, even if the signer is not part of the signer set that controls the public key locking the deposit.
This is largely a refactor, with the only functional change being that we always call the blocklist client. For that change I updated the relevant integration tests.
=> feat: run blocklist client for deposits that we cannot sign for

.github/actions/dockerfiles/Dockerfile.blocklist-client.debian, .github/workflows/image-build.yaml
Closes: #843
Adds publishing of the blocklist client docker compose.
Currently being tested locally, not tested yet.
=> feat: Add blocklist client publishing to dockerhub

emily/handler/src/api/handlers/internal.rs, emily/handler/src/database/accessors.rs
Closes: #526 
Prevents the possible underflow during a chainstate reorg: I swapped a `tip_height - 1` followed by an exclusive search of deposits/withdrawals modified after a height to an inclusive search of deposits/withdrawals modified from `tip_height`.
Described above.
Tested with integration tests.
=> feat: Address possible underflow during reorg

docker/sbtc/signer/signer-config.toml, signer/src/config/default.toml, signer/src/config/mod.rs, signer/src/network/libp2p/event_loop.rs
Just a little config option for enabling/disabling mDNS peer discovery -- mDNS is mostly useful in a dev/test setting (for our use-case), but I want to be 100% sure that we don't get any accidental mDNS discoveries in our testnet deploy to ensure that we're testing how real-world signers will discover eachother, i.e. force them to use seed addresses and WAN discovery via Kademlia.
I didn't add any explicit test for this, but I verified that disabling this value in `default.toml` breaks the existing tests (which rely on mDNS).
I disabled this for the `devenv` configs as those have explicit seeds.
=> feat: add config for disabling mdns

signer/src/bin/demo_cli.rs, signer/src/config/default.toml, signer/src/config/mod.rs, signer/src/context/signer_context.rs, signer/src/emily_client.rs, signer/src/main.rs
Adds API Keys to the Emily Client section of the signer config.
Closes: #748 
Adds a new configuration option for the EmilyConfig to include an api key for every endpoint.
- Updated the configuration documentation
- Updated relevant configuration creation functions
I added an additional configuration unit test.
I didn't include this in the PR, but I tested this with integration tests against a version of the API deployed that required API Keys. 
For each place in the `signer` integration tests that instantiated an API I replaced the old logic with an actual API and key.
```rust
let emily_client =
EmilyClient::try_from(&Url::parse("http://localhost:3031").unwrap()).unwrap();
```
Converted to
```rust
// We need to populate our databases, so let's fetch the data.
let emily_config = …
```
=> 748 feature emily client authentication

emily/cdk/lib/constants.ts, emily/cdk/lib/emily-stack-utils.ts, emily/cdk/lib/emily-stack.ts
Closes: #887 
Adds root domain name specification support to the cdk template generation via the following ENV variables.
- `CUSTOM_ROOT_DOMAIN_NAME` which is the root domain name
- `HOSTED_ZONE_ID` which is the hosted zone ID provided in the AWS console
Note that if the `CUSTOM_ROOT_DOMAIN_NAME=sbtc-emily.com` then the api will be deployed differently based on stage:
- `stAgE` -> `stAgE.sbtc-emily.com`
- `beta` -> `beta.sbtc-emily.com`
- `prod` -> `sbtc-emily.com`
Tested with a real deployment.
=> feat: Add custom root domain name option.

signer/src/testing/transaction_coordinator.rs, signer/src/testing/wsts.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs, signer/src/wsts_state_machine.rs
This PR changes `signer` to use the `WSTS` `fire::Coordinator` rather than the `frost::Coordinator`.  Whereas the `frost::Coordinator` will wait for all signers to send nonces when starting a signing round, the `fire::Coordinator` will take the first `threshold` of responders and attempt to sign with them.  
If a signer sends a nonce but does not send a signature share before the configured timeout, or sends a signature share that fails to verify, it is excluded from further signing, and another iteration of the current round is attempted.  So at every iteration, we either get a good signature, or we reduce the number of available signers.  Thus, we are guaranteed  to converge to a good signature or a failure. 
The `fire::Coordinator` can also run `DKG` with less than full participation, …
=> Use the fire coordinator to handle missing or malicious signers

signer/src/block_observer.rs, signer/src/main.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/emily.rs, signer/tests/integration/rbf.rs, signer/tests/integration/setup.rs, signer/tests/integration/transaction_coordinator.rs, signer/tests/integration/utxo_construction.rs
These are easy changes that came up in another branch.
* Remove the redundant fields of the block observer.
* Allow the max-fee to be set when creating deposit requests in integration tests.
This is a refactor, if tests pass then all is good.
=> refactor: simplify block observer

signer/migrations/0003__create_tables.sql
The other event tables do not have such a constraint, because we cannot know whether the transaction has been written to the table before the event.
* Remove the foreign key constraint
=> fix: remove the foreign key constraint on rotate-keys event table

signer/src/context/mod.rs, signer/src/context/signer_context.rs, signer/src/context/termination.rs, signer/src/error.rs, signer/src/lib.rs, signer/src/main.rs, signer/src/network/in_memory.rs, signer/src/network/in_memory2.rs, signer/src/network/libp2p/event_loop.rs, signer/src/network/libp2p/network.rs, signer/src/network/libp2p/swarm.rs, signer/src/network/mod.rs, signer/src/request_decider.rs, signer/src/testing/request_decider.rs, signer/src/testing/transaction_signer.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs, signer/tests/integration/communication.rs, signer/tests/integration/request_decider.rs, signer/tests/integration/transaction_coordinator.rs, signer/tests/integration/transaction_signer.rs
This might address a bug we're seeing on devnet.
I'm not entirely sure this fixes the issue, or if the issue was here at all. But this adds more logging and probably makes things better.
* Bump the stream capacity
* More eagerly send messages along.
=> fix: handle networking bug

signer/src/network/libp2p/event_loop.rs, signer/src/network/libp2p/swarm.rs
Removes the commented-out libp2p auto-nat/relay functionality as we're not using it right now and we don't know if it works; but now we have the changes saved in a PR if/when we want to revisit.
=> chore: remove commented out libp2p code

contracts/contracts/sbtc-deposit.clar, contracts/contracts/sbtc-registry.clar, contracts/tests/clarigen-types.ts, contracts/tests/sbtc-deposit.test.ts, contracts/tests/sbtc-withdrawal.test.ts
Updates two structs in the sbtc-registry contract to stored data already passed through.
Closes: #800 
The 'sbtc-registry' Clarity smart contract
All unit tests effected are now updated.
=> Updated Clarity Maps

contracts/contracts/sbtc-registry.clar, contracts/tests/clarigen-types.ts, signer/Cargo.toml, signer/src/emily_client.rs, signer/src/logging.rs, signer/src/main.rs, signer/src/network/libp2p/event_loop.rs, signer/src/network/libp2p/swarm.rs, signer/src/testing/transaction_signer.rs, signer/src/transaction_signer.rs, signer/tests/integration/transaction_coordinator.rs, signer/tests/integration/transaction_signer.rs, signers.sh
=> fix: demo branch fixes

signer/src/emily_client.rs, signer/src/logging.rs
We mistakenly took it out.
* Add back the target
* ~~Display the error~~, we want to see the request body when we get an error.
This shouldn't affect anything besides logs
=> feat: add back the target field in our logs

docker/sbtc/signer/Dockerfile
Add `ca-certificates` to signers image to enable connecting via https to Emily.
=> chore: add ca-certificates to docker image

signer/src/bitcoin/validation.rs, signer/src/error.rs, signer/src/message.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs, signer/src/wsts_state_machine.rs, signer/tests/integration/bitcoin_validation.rs, signer/tests/integration/transaction_signer.rs
Closes https://github.com/stacks-network/sbtc/issues/793, closes https://github.com/stacks-network/sbtc/issues/696, closes https://github.com/stacks-network/sbtc/issues/286, and closes https://github.com/stacks-network/sbtc/issues/296.
* Do the pre-validation check.
* Make sure the tx-signer checks the sighash in WSTS messages.
* Do not construct the Signers' BTC state in the tx-signer.
* Slight refactor to better reflect the meaning of things of what is being validated, which is the pre-sign request and not the bitcoin context.
I need to add some.
=> feat: ensure signers go through the bitcoin validation code path

.github/actions/dockerfiles/Dockerfile.blocklist-client.debian, .github/actions/dockerfiles/Dockerfile.signer.debian
There's a bug in the current CI Docker images that prevents Rust code from establishing TLS connections due to a lack of CA certificates. This fixes that.
Cherry-picked from #889.
=> fix: Install `ca-certificates` in CI images

signer/src/main.rs, signer/src/testing/transaction_coordinator.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/emily.rs, signer/tests/integration/transaction_coordinator.rs
A quick fix for testnet which raises the sleep time after pre-begin signing messages. Will be resolved properly in #956 .
=> fix: temporary timing fix (pre #956)

docker/sbtc/signer/signer-config.toml, envs/signer-1.env, envs/signer-2.env, envs/signer-3.env, signer/src/bin/demo_cli.rs, signer/src/config/default.toml, signer/src/config/mod.rs, signer/src/emily_client.rs
Changes the Emily endpoint config to a URI in the format `http(s)://[api-key@]<host>:<port>`.
Making this change primarily due to the fact that things aren't working well with environment variables and the URI format already supports authentication information.
- Modified the emily endpoint format in config
- Updated tests
- Updated demo-cli
- Added the env vars to the local signer `.env` files 1-3.
=> feat: change emily config to uri

contracts/contracts/sbtc-deposit.clar, contracts/contracts/sbtc-withdrawal.clar, contracts/tests/clarigen-types.ts
This small PR addresses two bugs for the Clarity contracts recently opened under a single issue.
Closes: #971 
Both changes mentioned in linked issue are implemented. Removed the unnecessary (ok ...) wrapper & reused the 'version-int' variable.
No new tests were added but all unit tests still intact.
=> Minor Clarity Issues

signer/src/request_decider.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/postgres.rs, signer/src/testing/storage.rs, signer/src/testing/storage/postgres.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/emily.rs, signer/tests/integration/postgres.rs, signer/tests/integration/request_decider.rs
Closes https://github.com/stacks-network/sbtc/issues/684
* Update the queries for `get_pending_deposit_requests` and `get_pending_withdrawal_requests` to ignore requests that the signer has voted on already.
* Update the in memory implementations of both functions.
* Add a helper query to maintain the same behavior in the `load_latest_deposit_requests_persists_requests_from_past` test.
This PR adds integration tests that check the new behavior of the updated queries.
=> feat: do not attempt to vote on requests more than once

signer/src/proto/convert.rs
Closes: https://github.com/stacks-network/sbtc/issues/991
Use `compress` to derive parity instead of `has_even_y()`
=> fix: fix Point proto conversion

signer/migrations/0003__create_tables.sql, signer/src/bitcoin/utxo.rs, signer/src/bitcoin/validation.rs, signer/src/block_observer.rs, signer/src/context/mod.rs, signer/src/context/signer_state.rs, signer/src/emily_client.rs, signer/src/error.rs, signer/src/main.rs, signer/src/request_decider.rs, signer/src/testing/block_observer.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/bitcoin_validation.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/emily.rs, signer/tests/integration/rbf.rs, signer/tests/integration/setup.rs, signer/tests/integration/transaction_coordinator.rs, signer/tests/integration/transaction_signer.rs, signer/tests/integration/utxo_construction.rs
Closes: #856
- `SbtcRequests` now filters out deposit requests that would cause the total transaction amount to exceed the cap.  
- The filtering logic is straightforward and processes deposits in the order they were received.
- Signers revalidate `BitcoinPreSignRequest` to ensure the total sum of deposits does not exceed the cap.  
- Individual transactions are also checked against the per-request cap in the validate function. (Maybe I should remove it from there and just merge the check on the `can_accept` field of the `SignerDepositDecision` - like in the original implementation from Cyle)
- A new `ValidationCache` struct caches `DepositRequestReport` and `SignerVotes` from the database.  
- This prevents redundant queries during pre-validation and per-request validation steps.
- Added …
=> Feat: validate deposits are below total and per-request-cap

signer/src/keys.rs
Closes https://github.com/stacks-network/sbtc/issues/999
* Go through the compressed point implementation when converting a `p256k1::point::Point` into the crate `PublicKey`.
This adds some tests to make sure that we do not get caught off-guard by the bug that we found.
=> fix: address the lingering bug when converting a `Point` into a `PublicKey`

signer/src/network/libp2p/event_loop.rs, signer/src/network/libp2p/network.rs
Closes https://github.com/stacks-network/sbtc/issues/979
* Check that the peer that published a message is in the current signing set.
This adds two tests, one for happy path gossiping and another for the check.
=> feat: check message source is in the current signing set

signer/src/request_decider.rs
Closes https://github.com/stacks-network/sbtc/issues/1046
This came up recently and the more natural position is to reject a deposit if any input into the transaction is invalid.
* Reject deposits if any of the inputs cannot be accepted.
I do not believe we use the blocklist client in tests so they should all pass.
=> fix: only accept deposits if all inputs are fine

signer/src/block_observer.rs, signer/src/context/signer_state.rs, signer/src/main.rs, signer/src/stacks/api.rs, signer/src/testing/stacks.rs, signer/src/testing/transaction_coordinator.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/emily.rs, signer/tests/integration/transaction_coordinator.rs
Closes: https://github.com/stacks-network/sbtc/issues/1026
In block observer `update_sbtc_limits`, check token total supply only if we have a total cap and the token contract exists.
Also remove some duplicated code in favor of a dummy const.
Added an integration test checking that block observer fully process a block in the different scenarios.
=> fix: don't ask for total supply if token doesn't exist

emily/cdk/lib/emily-stack.ts
Enable Point in Time Backup for the production and test environments, and disable it for local and dev environments. 
The local env is not supported so the variable is configured to undefined to omit the parameter in the Cloudformation template.
Closes: https://github.com/bitcoinl2labs/sbtc.testnet/issues/12
- Add DynamoDB Point in Time Backup
Deployed in Dev
=> feat: Enable DynamoDB Point in Time Backup

signer/migrations/0007__create_bitcoin_blockchain_from.sql, signer/migrations/0008__create_indices_bitcoin_tx_tables.sql, signer/src/bitcoin/validation.rs, signer/src/lib.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/postgres.rs, signer/src/testing/transaction_coordinator.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/bitcoin_validation.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/postgres.rs, signer/tests/integration/transaction_coordinator.rs, signer/tests/integration/transaction_signer.rs
Closes #1004 
* Add a new table valued function for getting the bitcoin blockchain until a certain height.
* Change the `get_signer_utxo` to not require the context window.
I added integration tests, but they need comments.
=> feat: remove need of context window for signers utxo

docker/prodlike/config/signer-config.toml, docker/sbtc/signer/signer-config.toml, signer/src/config/default.toml, signer/src/config/mod.rs, signer/src/stacks/api.rs, signer/tests/integration/block_observer.rs
Closes: #?
Remove unused `nakamoto_start_height` config -- we already use pox info for this, the config was probably a leftover. This is *not* a breaking-local since extra entries in toml are simply ignored.
Devenv demo script run okay.
=> chore: remove unused `nakamoto_start_height` config

contracts/contracts/sbtc-token.clar, contracts/tests/sbtc-token.test.ts
This PR adds a print statement to transfer function of sbtc token contract
Closes: #1090 
Adds extract event to transfer of sBTC tokens
Unit test added.
=> [sBTC] Make sBTC sip-10 compatible

emily/cdk/lib/emily-stack.ts
Closes: #N/A
- Fixes odd API key naming scheme I accidentally introduced in #897 
- Uses the right number of api keys per api
- Makes the api key names backwards compatible for the public endpoint
=> Backwards compatible api keys

contracts/contracts/sbtc-bootstrap-signers.clar, contracts/contracts/sbtc-deposit.clar, contracts/contracts/sbtc-token.clar, contracts/docs/sbtc-bootstrap-signers.md, contracts/tests/clarigen-types.ts, contracts/tests/sbtc-bootstrap-signers.test.ts, contracts/tests/sbtc-deposit.test.ts
Closes https://github.com/stacks-network/sbtc/issues/504 and closes https://github.com/stacks-network/sbtc/issues/1096.
* Made sure the highlighted code comments were accurate
* Fixed a lingering bug in the number of keys that are acceptable in `rotate-keys-wrapper` contract calls.
* Reduce the number of acceptable deposits in one `complete-deposits-wrapper` contract call down to 500. `pnpm test:report` complete successfully with this change.
This adds a test against the actual limit, that was missing when some of the function signatures were changed to accept 128 keys as opposed to 15.
=> fix: length bug in rotate-keys-wrapper contract call

docker/sbtc/signer/signer-config.toml, docker/testnet/config/signer-config.toml.sample, signer/src/bitcoin/client.rs, signer/src/bitcoin/mod.rs, signer/src/bitcoin/rpc.rs, signer/src/block_observer.rs, signer/src/config/default.toml, signer/src/config/mod.rs, signer/src/context/signer_context.rs, signer/src/context/signer_state.rs, signer/src/error.rs, signer/src/main.rs, signer/src/request_decider.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/block_observer.rs, signer/src/testing/context.rs, signer/src/testing/dummy.rs, signer/tests/integration/bitcoin_rpc.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/emily.rs, signer/tests/integration/postgres.rs, signer/tests/integration/setup.rs, signer/tests/integration/transaction_coordinator.rs
Closes https://github.com/stacks-network/sbtc/issues/685 as well.
This PR focuses on the bitcoin side of things. The OOM possibility applies much less to Stacks blocks.
* Add an optional config parameter that defines the minimum bitcoin block height for the signers. This means that the signers will have blocks for heights at least as high as the block set here. If the above parameter is unset, we use the nakamoto start height as the fallback value.
* Fetch bitcoin blocks all the way back to the last known block in the database. If there are no blocks in the database, then stop at the minimum block height defined above.
* Fetch historical bitcoin blocks by first fetching (slimmed down) block headers and then, once all block headers are known, fetch the bitcoin blocks one at a time. This …
=> feat: add bitcoin block start height to the signers

emily/cdk/lib/constants.ts, emily/cdk/lib/emily-stack-utils.ts, emily/cdk/lib/emily-stack.ts
Closes: #N/A
Changes various resource names so that api keys won't be overwritten, and so that nothing needs to changed manually to deploy on mainnet without issues.
The public api will now have no suffixes, but the others will.
Also created a new standard stage name for even more dev like environments `temp`.
Tested by deploying onto a real development environment
=> feat: Make emily api able to migrate

emily_sidecar/app.py, emily_sidecar/test.py
As detailed in [stacks-core issue #5558](https://github.com/stacks-network/stacks-core/issues/5558), we discovered that when connected to a syncing stacks-node, the node rarely sends POST requests to the configured event observers at the `/attachments/new` endpoint - even if the events observer is configured to filter only specific events. 
This issue was observed during a sync starting from the genesis block, though it is unclear whether it also occurs with more recent messages.
- added dummy handler for `/attachments/new`
- add unit tests to confirm that the enpoint always returns 200 whatever the input
=> feat: add attachments handler to the sidecar

docker/docker-compose.yml, docker/sbtc/docker-compose.yml, docker/sbtc/emily-sidecar/Dockerfile, docker/stacks/stacks-regtest-miner.toml, emily_sidecar/app.py, emily_sidecar/gunicorn_config.py
Update the port used by the emily-sidecar from 5000 to 20540. The reason for this change is that port 5000 is commonly used by various other applications and services, which can lead to conflicts during deployment or local development. Switching to a less commonly used port (20540) reduces the risk of such conflicts and ensures smoother operation.
- tested that the sidecar was still receiving update from the stacks-node and forwarding chainstate updates to emily in devenv
=> chore: change sidecar port 5000->20540

emily_sidecar/app.py
Improve logs of the sidecar, previously it was flooded by the events received by the stacks node, and difficult to read.
- logs event validation errors
- logs sidecar configuration 
- simplify the information logged to just the chainstate and not the full events.
=> chore: improve sidecar logs

emily/cdk/lib/emily-stack.ts
This PR fixes a problem in the beta environment where we use the DNS delegation with the prod account.  This account is not able to create an alias beta.private.* but only private.beta.*
- Swap stage and prefix
=> Swap custom domain prefix to support beta environment dns limitation

signer/src/stacks/contracts.rs, signer/src/stacks/events.rs, signer/src/storage/model.rs
Closes https://github.com/stacks-network/sbtc/issues/1102
* Add traits for converting to and from little-endian byte order. Implement them for bitcoin `Txid` and `BlockHash` types.
* Convert bitcoin txid and block hash types to little-endian byte order for all contract calls transactions.
I tested this out on local devenv.
=> feat: use consistent hash endianness in contract calls

signer/src/error.rs, signer/src/keys.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/postgres.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs, signer/src/wsts_state_machine.rs, signer/tests/integration/stacks_events_observer.rs
Closes https://github.com/stacks-network/sbtc/issues/1114
* Construct the WSTS coordinator state machine using the correct DKG shares.
* Do not run DKG if it has been run before.
* Remove some currently unused code. The tests that exercise that code path have already been ignored.
No tests yet, hence the draft status.
=> fix: run DKG only once

emily/handler/src/database/entries/deposit.rs, emily/handler/src/database/entries/withdrawal.rs
Closes: #N/A
There's an issue with the reorg logic where the reorg updates the height, but it doesn't update the hash or fulfillment.
Updates the reorganizing behavior to fix the bug.
Added unit tests for the reorganizing.
> Note: This is currently failing due to the intermittent swatinem caching error, but the tests are passing: [link](https://github.com/stacks-network/sbtc/actions/runs/12315906307/job/34375058287?pr=1120)
=> fix: Update block hash along with reorg.

signer/tests/integration/bitcoin_validation.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/postgres.rs
We've been running out of disk space in CI. These changes should fix that... hopefully.
Maybe one day we'll create a procedural macro, like the one that `sqlx` has that does this cleanup for you.
* Delete databases at the end of integration tests.
If tests are green then we're good.
=> ci: clean up databases in integration tests

signer/src/bitcoin/utxo.rs, signer/src/bitcoin/validation.rs, signer/src/lib.rs, signer/src/stacks/contracts.rs, signer/src/testing/block_observer.rs, signer/tests/integration/complete_deposit.rs, signer/tests/integration/setup.rs
Closes https://github.com/stacks-network/sbtc/issues/1135 and closes https://github.com/stacks-network/sbtc/issues/1174.
This is technically protocol breaking, because now signers may reject requests for inclusion into a bitcoin transaction when before they wouldn't. Practically speaking, this has no effect since the current sBTC limits filter out these deposit requests as already.
* Only consider deposits where the mint amount is above the dust limit.
* Check for the mint amount during bitcoin validation.
* Check for the mint amount during stacks validation.
* Don't be so wasteful during the happy path.
* Do less work during the happy path when unwrapping stuff.
This PR adds an integration test that is crappier than our other integration tests. It's not flaky, just complex.
=> fix: ensure mint amount is greater than the dust limit

emily_sidecar/app.py, emily_sidecar/test.py
Previously, when the sidecar stripped the 0x prefix from the index_block_hash, it inadvertently removed additional leading zeros that followed the prefix. For example, `0x0012abc` was transformed into `12abc` instead of the correct `0012abc`.
Currently, Emily is storing multiple chainstate hashes with missing leading zeros. This issue will be resolved with a database pass, prepending zeros to the start of any hashes with fewer than 64 characters.
- substituted `lstrip` with `removeprefix`
- added a unit test
=> fix: sidecar hash prefix strip on chainstate

Cargo.lock, signer/Cargo.toml, signer/src/api/mod.rs, signer/src/api/router.rs, signer/src/main.rs
The sBTC signers stalled their Stacks nodes in prod when the nodes emitted "attachment" events (which is a known bug on the node-side), and the sBTC signers couldn't handle it.
This adds a dummy endpoint responding with 200 OK.
Add simple test, and tested that everything else still works via devenv demo script.
=> fix: add handler for new attachments

signer/src/bitcoin/utxo.rs, signer/src/bitcoin/validation.rs, signer/src/error.rs
Closes https://github.com/stacks-network/sbtc/issues/1189.
* Reject a `BitcoinPreSignRequest` if it does not contain any deposit or withdrawal requests.
* Reject fee rates that are not strictly positive.
* Make sure pre-validation checks run before everything else during bitcoin validation.
I tested that the changes here solve the issue on local devnet.
=> fix: reject empty pre-sign requests

.generated-sources/emily/client/rust/private/src/apis/deposit_api.rs, .generated-sources/emily/client/rust/public/src/apis/deposit_api.rs, .generated-sources/emily/client/rust/testing/src/apis/deposit_api.rs, signer/src/api/new_block.rs, signer/src/api/router.rs
Closes: https://github.com/stacks-network/sbtc/issues/1186
Increase the body max size to 8MB for the event observer endpoint. Also add some codegen leftover from some other PR.
Add 2 tests to check the limit boundary.
=> fix: increase the event observer max body size

docker/docker-compose.ci.yml, docker/docker-compose.test.yml, signer/src/stacks/api.rs, signer/src/testing/storage.rs, signer/tests/integration/bitcoin_validation.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/complete_deposit.rs, signer/tests/integration/emily.rs, signer/tests/integration/postgres.rs, signer/tests/integration/request_decider.rs, signer/tests/integration/rotate_keys.rs, signer/tests/integration/transaction_coordinator.rs, signer/tests/integration/transaction_signer.rs, signer/tests/integration/withdrawal_accept.rs
The integration-env completely broke for me causing me to be unable to run integration tests locally and I'm not sure what the root cause actually was, but I kept getting a lot of failures with errors that looked like concurrency issues (despite that we're using single-threaded). It seemed to be related to creating databases using a template 🤷 
This refactor fixed the issues for me anyway and simplifies the code a bit.
- Now uses a sequence in the database for `db_num`.
- The `new_test_database()` method is now a bit more streamlined -- I removed the parameters since we never use them, and it's now much simpler/smaller.
=> refactor: better integration test db instantiation

signer/src/api/new_block.rs
Adds a little additional logging to the `new_block` event observer handler to help with healthchecks of partner signers. This will now record the block hash, height, parent and bitcoin anchor for log events within the handler.
- Additional logging and tracing spans
- Minor refactors to help optimize how/when the log lines are written and so they include the relevant fields
=> feat: additional logging for `new_block` handler

docker/mainnet/sbtc-signer/signer-config.toml.in, docker/sbtc/signer/signer-config.toml, signer/src/config/default.toml, signer/src/config/mod.rs
Closes: #1201 
Closes: #1207 
Adds the configuration parameter `dkg_rerun_bitcoin_height` (don't love the name) and `dkg_rounds_target` in preparation for #1199 and #1200.
I made this optional for now (contrary to #1201 requesting required) because I'm not sure how we want this to behave when it comes to devenv etc. -- required would mean that devenv needs to run two DKG's, maybe we don't want that? So I can change it to required after we discuss the implications if we want.
- Adds one new test for each of the config parameters for testing reading the default configuration and env var.
=> feat: add config params for dkg-rerun bitcoin block height and target rounds

signer/src/config/mod.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/postgres.rs, signer/src/transaction_signer.rs
Closes: #1200 
Changes the check in the `handle_wsts_message` method for `DkgBegin` messages in the transaction signer to conditionally allow a second DKG run if:
- There has not been a DKG run yet (i.e. no entries in the signer's `dkg_shares` db table), **OR**
- If DKG has been run exactly once (one entry in the signer's `dkg_shares` db table) **AND** a DKG re-run height is configured **AND** the current bitcoin chain tip height is >= the configured re-run height
This copies a snippet of the config code in #1201 to be able to retrieve the config value for the DKG re-run height.
This currently lacks additional tests because my integration env is borked for some reason; looking into that now.
=> feat: #1200 feature signers allow second dkg after specific block height

signer/src/config/mod.rs, signer/src/error.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/transaction_coordinator.rs
Closes: #1199
Introduces similar logic to #1200 for the transaction coordinator when determining if DKG should be run or not. If the current state of the signer and the configuration allow, the coordinator will attempt a new round of DKG.
Added a new test `run_subsequent_dkg` which is very similar to the existing `run_dkg_from_scratch` test, but with its starting point that one DKG round has been completed successfully.
=> feat: #1199 feature coordinator attempts subsequent DKG run according to configuration

signer/src/transaction_coordinator.rs
Closes https://github.com/stacks-network/sbtc/issues/1214
* Return early in `TxCoordinatorEventLoop::construct_and_send_bitcoin_presign_request` if there are no transactions to handle.
I did not add a test because it would take quite a while to setup. Perhaps I should create a ticket to add a test at some later date.
=> fix: exit early if no requests during presign request creation

sbtc/src/deposits.rs, sbtc/src/error.rs, sbtc/tests/integration/validation.rs, signer/src/block_observer.rs, signer/tests/integration/utxo_construction.rs
Closes https://github.com/stacks-network/sbtc/issues/1228
* Validate the network of the Stacks recipient address during deposit validation.
Two unit tests were added into the sbtc crate, which should be sufficient.
=> fix: validate network recipient stacks address

.github/actions/dockerfiles/Dockerfile.blocklist-client.debian, .github/actions/dockerfiles/Dockerfile.signer.debian
Use --locked flag for release builds
Closes: https://github.com/stacks-network/sbtc/issues/1225
- Add locked option in the docker build
=> feat: Use --locked flag for release builds

docker/electrs/Dockerfile
`electrs` as we use it today introduced `nightly` rust features and thus failed to build. This updates the `Dockerfile` to install `rustup` + `nightly` and install `electrs` using nightly.
=> chore: fix elecrs to use nightly in devenv

.github/workflows/image-build.yaml
Add Artifact attestation for CI
Closes: https://github.com/stacks-network/sbtc/issues/1233
Ref: https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds#generating-artifact-attestations-for-your-builds
- Add Github Artifact Attestation in the docker build workflow
https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds#generating-artifact-attestations-for-your-builds
=> feat: Add Artifact attestation for CI builds

.github/workflows/buf-ci.yaml, .github/workflows/contract-tests.yaml, .github/workflows/unit-tests.yaml
Ensure GitHub workflows have only read permissions (unless needed) 
Closes: https://github.com/stacks-network/sbtc/issues/1234
- Add permission block to enforce permission visibility
=> feat: Ensure GitHub workflows have only read permissions (unless needed) 

signer/src/bitcoin/utxo.rs, signer/src/context/signer_context.rs, signer/src/context/signer_state.rs, signer/src/testing/block_observer.rs, signer/tests/integration/bitcoin_validation.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/contracts.rs, signer/tests/integration/rbf.rs, signer/tests/integration/setup.rs, signer/tests/integration/transaction_coordinator.rs, signer/tests/integration/transaction_signer.rs, signer/tests/integration/utxo_construction.rs
Closes: https://github.com/stacks-network/sbtc/issues/1245
Set the initial sBTC limits to zero.
Also removed some `setup_logging` left overs.
Add an integration test (without the limit changes it was minting, now it doesn't).
=> feat: use conservative default sBTC limits

Cargo.lock, protobufs/crypto/wsts/wsts.proto, signer/Cargo.toml, signer/src/proto/convert.rs, signer/src/proto/generated/crypto.wsts.rs, signer/src/wsts_state_machine.rs
WSTS signer state machines now take a parameter for the DKG key threshold. This PR uses that commit and we make changes after their API changed.
* Update the version of WSTS
* Update the protobufs after the new change
* Update our use of WSTS signer state machines after the API change.
This is a dependency update, where the dependency, WSTS, is more strict. If tests pass then we should be good to go.
=> chore: bump wsts revision

Cargo.lock, Cargo.toml, signer/src/storage/in_memory.rs, signer/tests/integration/postgres.rs, signers.sh, supply-chain/config.toml
Fix a difference between the in memory and pg implementation of `get_stacks_chain_tip`, follow up for the broken test after the `fake` (non) bump in https://github.com/stacks-network/sbtc/pull/1271.
Bump `fake` and fix the in memory implementation of `get_stacks_chain_tip` to align it to the pg implementation, by changing the endianness of the stacks block hash used for tie breaking.
The "broken" test now passes, and add two test to compare the get chain tip between the pg and in memory stores.
=> fix: use the same sorting key for in memory impl of stacks chain tip

signer/src/transaction_signer.rs
Closes: https://github.com/stacks-network/sbtc/issues/1176
Add a canonical tip check in the messages coming from the coordinator mentioned in the issue.
Add test to check we indeed stop early in case of messages from non canonical tips.
=> feat: reject coordinator wsts messages from non canonical tips

signer/src/bitcoin/validation.rs, signer/src/bitcoin/zmq.rs, signer/src/block_observer.rs, signer/src/context/signer_state.rs, signer/src/main.rs, signer/src/testing/btc.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/transaction_coordinator.rs, signer/tests/integration/transaction_signer.rs, signer/tests/integration/zmq.rs
Closes https://github.com/stacks-network/sbtc/issues/1295.
1. Store the current signer set and aggregate key in the signer state at the end of the block observer.
2. Change the event loops to use the signer state when they need the current signer set or current aggregate key.
3. Changes in the current signer set now affect who the signers can communicate to. This is fine for now, since we do not support changing the current signing set from the bootstrap signer set.
4. Clean up the creation of a block hash stream, particularly in tests.
This PR adds a new integration test for the expected behavior of the block observer. It also moves around another test, and removes a test that was duplicated. The existing integration tests should catch anything else that might be amiss, but I also tested …
=> feat: cache key-rotation data block observer

Cargo.lock, Cargo.toml, protobufs/stacks/signer/v1/messages.proto, signer/src/message.rs, signer/src/proto/convert.rs, signer/src/proto/generated/stacks.signer.v1.rs, signer/src/testing/message.rs, signer/src/testing/transaction_coordinator.rs, signer/src/testing/transaction_signer.rs, signer/src/testing/wsts.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs, signer/src/wsts_state_machine.rs, signer/tests/integration/emily.rs, signer/tests/integration/postgres.rs, signer/tests/integration/transaction_coordinator.rs, signer/tests/integration/transaction_signer.rs, supply-chain/config.toml
A breakout PR from #1285 to move some of the more refactor-like changes related to WSTS.
Part of: #1300
⚠️ This PR's branch is targeted by #1285 which needs to merge into this branch before merging this PR into `main`.
- Rename `WstsMessage.txid` to `id` and use a `WstsMessageId` enum instead of a `bitcoin::Txid`.
- Protobufs updated in a backwards-compatible way, deprecating the `txid` field (flagging this `breaking-protocol` anyway, just in-case).
- Generated proto code updated.
- `StateMachineId` is now an enum instead of a newtype over `[u8; 32]`.
- A fair bit of restructuring/cleanup in `wsts_state_machine.rs`. **This is the bulk of the changes in this PR**
- Some logging improvements.
- Updates `wsts` to [this commit](https://github.com/Trust-Machines/wsts/commit/a7bf38bd54cddf0b78c0 …
=> refactor: wsts-related cleanup

signer/migrations/0003__create_tables.sql, signer/migrations/0013__consolidate_withdrawal_tables.sql, signer/src/api/new_block.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/dummy.rs, signer/src/testing/request_decider.rs, signer/src/testing/transaction_coordinator.rs, signer/tests/integration/postgres.rs, signer/tests/integration/setup.rs
Closes: #1329
- drop `sbtc_signer.withdrawal_create_events` 
- drop FK to stacks_blocks from `withdrawal_requests`
- add missing `block_height` column to `withdrawal_requests`  ( received from the event)
- new withdrawal events received in the `new-block` handler are not saved into `withdrawal_requests`
- adapted queries
- fix `get_withdrawal_requests` in_memory implementation to include the withdrawals in the anchored to the block at window boundary.
- updated unit and integration tests
- migrations results are tested by `writing_withdrawal_requests_postgres`
- needed to change random seed for `assert_should_store_decisions_received_from_other_signers` - with the current changes, the previous seed was generating 25 valid deposits, instead of the 30 expected, causing the test to fail
-
=> [chore] consolidate withdrawals tables

signer/src/error.rs, signer/src/keys.rs, signer/src/transaction_signer.rs, signer/tests/integration/postgres.rs, signer/tests/integration/transaction_signer.rs
Had forgotten that I had these stashed -- might as well have them, so I did a quick cleaning and here they are.
- Adds a few integration tests for dkg verification. Not a complete suite, just a few that I had stashed the other day.
- Changes `Error::AggregateKeyMismatch` to struct syntax and makes a little logging tweak.
- Fixes a few random spelling mistakes.
=> feat: some dkg verification integration tests

Cargo.lock, Cargo.toml, blocklist-client/tests/tls_checking.rs, signer/tests/integration/main.rs, signer/tests/integration/tls_checking.rs, supply-chain/audits.toml
We accidentally disabled TLS support in reqwests and none of our tests caught it. That has been fixed.
I have branched off of tag `0.0.9-rc7` here.
* Enable TLS using `rustls` for the reqwests library
* Add some simple tests that fail if we disable it in reqwests.
=> fix: enable TLS in the blocklist client

signer/src/bitcoin/validation.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/tests/integration/bitcoin_validation.rs, signer/tests/integration/postgres.rs, signer/tests/integration/transaction_signer.rs
Closes https://github.com/stacks-network/sbtc/issues/1308.
1. Add three new queries that together construct the withdrawal request report.
2. Made some modifications to the `WithdrawalRequestReport` that make it easier to do https://github.com/stacks-network/sbtc/issues/1323.
This PR adds a bunch of integration tests, checking that the values in the report are valid. I still need to add some comments to the tests, but this is ready for review.
=> feat: implement query returning `WithdrawalRequestReport`

docker/stacks/stacks-regtest-miner.toml, signer/src/bin/demo_cli.rs, signers.sh
Closes: https://github.com/stacks-network/sbtc/issues/1331
Add `withdraw` to `demo-cli` to issue a `initiate-withdrawal-request` to the sBTC contract. Also cleanup a bit the demo-cli and added a bunch of defaults (for devenv) so that only the amount is required.
Now the `amount` specified in the cli (for both deposits and withdrawals) includes the `max_fee`.
Tested in devenv:
```
./signers.sh demo # usual donation + deposit
cargo run -p signer --bin demo-cli deposit --amount 100000
cargo run -p signer --bin demo-cli withdraw --amount 100000
```
The contract call is accepted (and funds locked), then the events are then picked up by the signers event observer, and a new request is created on Emily (we should probably move this to the sidecar).
=> feat: add withdraw to demo-cli

Cargo.lock, Cargo.toml, blocklist-client/tests/tls_checking.rs, signer/tests/integration/main.rs, signer/tests/integration/tls_checking.rs, supply-chain/audits.toml
* Enable TLS using rustls for the workspace
* Add an integration test for TLS in the blocklist client and the signer 
* Audit the new webpki-roots dependency
=> fix: enable TLS in the blocklist client (#1349)

signers.sh
These are just a couple of small `signers.sh` shell improvements
* Only build the binary once for all signers.
* Don't bring down the database when stopping the signers.
Hat tip to @tonyjzhou for pointing me to these fixes.
=> chore: small `signers.sh` fixes

signer/src/error.rs, signer/src/storage/model.rs, signer/src/testing/transaction_coordinator.rs, signer/src/transaction_coordinator.rs
Closes: #564 
- add `construct_withdrawal_accept_stacks_sign_request` method to the coordinator
- add a unit test
=> feat: create accept withdrawal transactions

signer/src/storage/in_memory.rs, signer/src/testing/request_decider.rs, signer/src/testing/storage/model.rs
Closes: #?
There was a bug in how we generate the stacks chain via `TestData`, constraining the stacks chain to a single bitcoin blocks. This fixes it and a couple of tests that were affected by the change.
Add a test to ensure we generate stacks chain spanning multiple blocks.
=> fix: correctly generate stacks chain in TestData

flake.lock
Context: `flake.lock` pins to a `git rev`. The previous one was pointing at a commit that didn't include the pre-built Rust 1.84 compiler. This fixes it.
=> Updates `flake.lock` so that `rust-overlay` includes Rust 1.84

signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/postgres.rs, signer/tests/integration/postgres.rs
Closes: https://github.com/stacks-network/sbtc/issues/1354
Implement `get_pending_rejected_withdrawal_requests` to get requests that must be rejected via a contract call.
Add tests covering different scenarios.
=> feat: query for pending rejected withdrawals

.github/workflows/image-build.yaml
Fixes a small annoyance as long as we don't get automated builds to ECR (https://github.com/stacks-network/sbtc/issues/1305).
=> feat: Disable nightly Docker builds on CI

docker/mainnet/nodes/docker-compose.chains.yml, docker/mainnet/nodes/stacks/Config.toml.in
Remove the RPC Bitcoin connection
Following a PR for the documentation.
Closes: https://github.com/stacks-network/sbtc/issues/1309
- Remove RPC Bitcoin connection from the docker-compose examples
=> fix: Remove Bitcoin RPC

docker/docker-compose.yml
Address https://github.com/stacks-network/sbtc/issues/1384
Follow up for https://github.com/stacks-network/sbtc/pull/1307
We removed the `bitcoin` Dockerfile, but the miner was still referencing it. We didn't catch this because we didn't try to rebuild the whole stack and devenv doesn't run in CI.
A possible downside of the current approach is that we require a network connection for the container to start up (this applies to `stacks-node`, `stacks-signer-*` and `bitcoin-miner`), so it's not possible to run devenv offline.
Tested with `docker compose -f docker/docker-compose.yml --profile default --profile bitcoin-mempool --profile sbtc-signer build --no-cache --pull` (+ usual demo run).
=> chore: fix bitcoin-miner image in devenv

signer/src/bitcoin/validation.rs
This PR updates the 'is_unique' validation inside the 'pre_validation' checker. Specifically, this update swaps out the logic of checking the uniqueness of a withdrawal 'QualifiedRequestID' with checking the uniqueness of a withdrawal on-chain 'RequestID' (a property found in the withdrawal QualifiedRequestID).
Closes: #1375 
Changes were made to the 'is_unique' helper found inside the 'pre_validation' function found inside the 'validation.rs' file within 'signer'.
A test was updated to match the fail-case scenario here (the same request_id within the same tx). Additionally, a handful of other tests were updated to fail correctly (aka adhere to the name given).
=> [feat] Update Withdrawal Request Validation

signer/src/storage/postgres.rs, signer/tests/integration/postgres.rs
Closes: #?
Fix the swept withdrawal query to cover for the case of forked events: if we have a canonical accept event and a forked one, we should still consider the request as accepted (and not return it).
Add a check in an existing test.
=> fix: swept withdrawal in case of forked accepts

signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/model.rs, signer/src/storage/postgres.rs, signer/src/testing/transaction_coordinator.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/transaction_coordinator.rs
Closes: https://github.com/stacks-network/sbtc/issues/568
Add the withdrawal rejection to the coordinator event loop. Also add a query to fetch all the valid withdrawal outputs, required to check if any is in mempool and we want to skip rejection.
Add a test checking the _off-query_ conditions for skipping a rejection (already accepted in the contract or output tx in mempool).
=> feat: add withdrawal rejection to the coordinator loop

.generated-sources/emily/client/rust/private/docs/HealthApi.md, .generated-sources/emily/client/rust/private/src/apis/health_api.rs, .generated-sources/emily/client/rust/public/docs/HealthApi.md, .generated-sources/emily/client/rust/public/src/apis/health_api.rs, .generated-sources/emily/client/rust/testing/docs/HealthApi.md, .generated-sources/emily/client/rust/testing/src/apis/health_api.rs, emily/handler/src/api/handlers/health.rs, emily/handler/src/api/routes/mod.rs, emily/openapi-gen/generated-specs/private-emily-openapi-spec.json, emily/openapi-gen/generated-specs/public-emily-openapi-spec.json, emily/openapi-gen/generated-specs/testing-emily-openapi-spec.json
The health endpoint was locked behind an API key. We don't need that. 
- remove the ApiGatewayKey requirement from the health endpoint
- fix routes
=> [fix] remove api key requirement from health endpoint

signer/src/stacks/contracts.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/postgres.rs, signer/src/testing/dummy.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/postgres.rs, signer/tests/integration/setup.rs, signer/tests/integration/transaction_coordinator.rs, signer/tests/integration/withdrawal_reject.rs
Closes https://github.com/stacks-network/sbtc/issues/1407
* Add in a validation check that looks for "active" withdrawals. These are withdrawals where it's possible that a fork could make the transaction valid in the eyes of the bitcoin network.
* Made sure that the coordinator did the same "is active" check when selecting requests to reject.
So far this PR has added one test. The comments in it are likely wrong and stuff, and it needs a little polish. I will fix that all up and add more tests.
=> feat: feature wait before rejecting a withdrawal request

Cargo.lock, Cargo.toml, signer/src/dkg/verification.rs, signer/src/testing/wsts.rs, signer/src/transaction_signer.rs, signer/src/wsts_state_machine.rs, supply-chain/audits.toml, supply-chain/config.toml
Update the `wsts` dependency to `13.0.0`
Closes #1162, closes #1166, and closes #1167
=> Update to wsts 13

signer/src/proto/convert.rs, signer/src/storage/in_memory.rs, signer/src/storage/mod.rs, signer/src/storage/postgres.rs
Closes: #?
Two nits about removing no longer used code we didn't squeeze in during the crunch:
- Remove `get_withdrawal_outputs`: replaced by `is_withdrawal_inflight`
- Proto convert wrappers for tests: now they derive eq (after https://github.com/stacks-network/sbtc/pull/1265)
=> [chore] Remove no longer used code

signer/src/network/libp2p/event_loop.rs
Closes: #1419
Removes the `continue` statement upon p2p peer connection rejection which otherwise prevents the event loop from continuing to outbound message processing.
All existing tests pass.
=> chore: don't `continue` on rejected peer connection

.github/workflows/image-build-and-draft-release.yaml, .github/workflows/nightly-image-build.yaml
Push nighties docker images to AWS ECR.
A separate flow for the scheduled and manual pushes is created, and a new GitHub private env.
Infra: https://github.com/BitcoinL2-Labs/sbtc.infrastructure/pull/54
Closes: https://github.com/stacks-network/sbtc/issues/1305
- Add new Workflow for ECR
- Config new env
https://github.com/stacks-network/sbtc/actions/runs/13571823794
https://376129863319-mqknrpsc.eu-west-1.console.aws.amazon.com/ecr/repositories/private/376129863319/sbtc?region=eu-west-1
=> feat: Push nighties docker images to AWS ECR

.generated-sources/emily/client/rust/public/.openapi-generator/FILES, .generated-sources/emily/client/rust/public/README.md, .generated-sources/emily/client/rust/public/docs/CorsApi.md, .generated-sources/emily/client/rust/public/src/apis/cors_api.rs, .generated-sources/emily/client/rust/public/src/apis/mod.rs, Cargo.lock, emily/openapi-gen/generated-specs/public-emily-openapi-spec.json, emily/openapi-gen/generators/public.rs, signer/Cargo.toml, signer/tests/integration/block_observer.rs, signer/tests/integration/emily.rs, signer/tests/integration/request_decider.rs, signer/tests/integration/setup.rs, signer/tests/integration/transaction_coordinator.rs
Closes #1444 
The endpoint was already disabled in the private API (used by the sidecar) and will now only be accessible through the testing API and client.
I'm not very happy with the `as_testing()` method and am open to suggestions. Ideally, all test calls to Emily should go through the test-emily-client, but this would require a larger refactor since the structs used in the two crates are different.
- disable the wipe_databases endoint.
- add the test-emily-client crate to the dev configuration of the signer.
- use the test-emily-client crate to call the wipe-databases.
=> 1444 chorebug restrict wipe databases to testing api

docker/docker-compose.yml, signer/src/bin/demo_cli.rs
Follow up for https://github.com/stacks-network/sbtc/issues/1441
- Add the missing envs to the compose
- Expose the bridge on 3000 to make leather `sBTC Devenv` working as expected
- Add `fund-btc` (and `fund-stx`) to demo cli to fund accounts
Did a bridge deposit, it worked (almost completely): because of https://github.com/stacks-network/sbtc/pull/1421, deposits are no longer marked confirmed by the signers, so the deposit will be fulfilled but not marked as such on the bridge. Once the sidecar is updated (https://github.com/stacks-network/sbtc/pull/1409 & co) it should work as expected.
Note that to rebuild the bridge you need `--no-cache`:
```
docker compose -f docker/docker-compose.yml --profile default build --no-cache sbtc-bridge-website
```
To fund your BTC account you can:
``` …
```
=> chore: update devenv for the bridge

.github/workflows/cargo-vet.yaml
We're getting CI issues for using ubuntu 20.04, so let's upgrade
* Change the version of ubuntu used in CI for cargo vet.
=> ci: use ubuntu 24.04 for cargo vet

signer/src/storage/postgres.rs, signer/tests/integration/postgres.rs
Closes: #?
The `get_swept_deposit_requests` and `get_swept_withdrawal_requests` queries may return completed requests as swept and pending if the relative completed events are anchored to a bitcoin block that precede the sweep bitcoin block.
This is fine as we have other layers taking care of this:
- The signers validating the contract call will ask the stacks node it the request is still pending
- The contracts rejecting replay
This PR add comments about it.
Add a test to show this situation.
=> chore: add comments for `get_swept_*` queries near context boundary

signer/src/api/new_block.rs, signer/src/emily_client.rs, signer/src/testing/block_observer.rs, signer/src/testing/context.rs
Remove the implementation of two private endpoints from the signer's emily-client. Those endpoints will be remove from the Public API and the signers will not have access to the autogenerated client code that are currently importing.
- remove `create_withdrawals` - The withdrawals will be created from the `new-block`  calls from the private API.
- remove `set_chainstate` - Only the sidecar can set a chainstate from the private API.
- remove mocking of the endpoints above in a few tests.
=> chore: remove signer's emily-client implementations to call private endpoints

emily/handler/tests/integration/withdrawal.rs
#1383 merge added a new field `recipient` to the withdrawal requests, that #1472 didn't pull in before the merge. 
- add the sender field to the test
=> [fix] add missing sender field after merge

signer/src/transaction_coordinator.rs, signer/tests/integration/transaction_coordinator.rs
Closes: https://github.com/stacks-network/sbtc/issues/1483
Add a `is_deposit_completed` call in the coordinator before calling `construct_deposit_stacks_sign_request` (and starting the signing round). Also nit a couple of logs for consistency.
Add a test to ensure the coordinator do/don't try a signing round based on the deposit status.
=> feature: coordinator checks deposit status before mint signing round

emily/handler/tests/integration/deposit.rs, emily/handler/tests/integration/withdrawal.rs
Fixes the test that were occasionally failing in CI. As described in [here ](https://github.com/frondeus/test-case/pull/48), that's a known problem in the test_case library. It requires the tokio::test to be defined after the test cases
Note that I wasn't able to reproduce the error locally.
- move tokio::test definition after the test cases
=> fix: random update_withdrawals_is_forbidden fails

emily/handler/src/context.rs
On deployment, the we are logging the settings of the lambda.
https://github.com/stacks-network/sbtc/blob/394dc72e5bc31db2e51d88f3f7445a724072fa56/emily/handler/src/bin/emily-lambda.rs#L21
This PR modifies the Debug implementation of the EmilyContext to not display the api key.
- modify Debug implementation of EmilyContext to write each field one by one, but explicitly redacting the trusted api key.
=> fix: stop logging the trusted api key on deployment

signer/src/proto/convert.rs, signer/src/stacks/contracts.rs, signer/src/testing/dummy.rs, signer/src/testing/message.rs, signer/src/testing/transaction_coordinator.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/contracts.rs, signer/tests/integration/postgres.rs, signer/tests/integration/withdrawal_accept.rs, signer/tests/integration/withdrawal_reject.rs
Closes https://github.com/stacks-network/sbtc/issues/1505
* Change the bitmap field from the internal structs to be `u128`s.
* Remove the validation checks for the bitmap from within the `AcceptWithdrawalV1::validate` and `RejectWithdrawalV1::validate` functions.
* Remove the integration tests that checked the bitmaps.
This is mainly a refactor that fixes a potential vulnerability. So if tests pass, then everything is fine.
=> feat: remove signer vote bitmaps from transactions

signer/tests/integration/transaction_coordinator.rs
There's a swallowed panic in the `transaction_coordinator::test_conservative_initial_sbtc_limits` test's sub-tasks due to a missing `EmilyInteract` mock expectation for `accept_withdrawals()`. This adds an expectation, copying what's done for deposits and fixing the panic.
=> fix `test_conservative_initial_sbtc_limits` test

docker/docker-compose.yml
While offline, I found out that `devenv` wouldn't start because we need connectivity to `apt-install` a few packages.
This PR proposes a poor-man's version of those packages (`jq` and `devenv`) that relies on binaries already including within the container image.
It's probably poor (if the image updates, this will break). But then, even doing `apt-get install` at container startup was poor :)
=> fix: Allow re-starting devenv while offline

.github/workflows/on-push.yaml
Adds the `pull_request` trigger to the `on-push` workflow so that PR's from external forks run.
=> chore(ci): add pull_request trigger to on-push workflow

.github/actions/dockerfiles/Dockerfile.blocklist-client.debian, .github/actions/dockerfiles/Dockerfile.signer.debian, README.md, docker/sbtc/Dockerfile, emily/handler/src/api/handlers/internal.rs, rust-toolchain.toml, sbtc/src/idpack/segmenters/bitmap.rs, signer/src/bitcoin/packaging.rs, signer/src/bitcoin/utxo.rs
Bumps rust to [1.86.0](https://blog.rust-lang.org/2025/04/03/Rust-1.86.0.html) and fixes a few new clippy lints. 
- Updates `rust-toolchain.toml` to use rust 1.86
- Fixes new/updated clippy lints
=> chore: bump rust to 1.86.0

.github/workflows/on-push.yaml
Turns out we ran into the issue of concurrently running (same) workflows for push + PR, this attempts to resolve it.
Changes the concurrency grouping to use `${{ github.workflow }}-${{ github.head_ref || github.ref }}` instead of only `github.ref`. `github.head_ref` is apparently used for PRs, and `github.ref` for pushes. This should hopefully result in them being the same for both...
=> chore(ci): fix double CI-runs between PR and push

sbtc/src/lib.rs, signer/src/bitcoin/rpc.rs, signer/src/block_observer.rs, signer/src/error.rs, signer/src/storage/postgres.rs, signer/tests/integration/block_observer.rs, signer/tests/integration/complete_deposit.rs, signer/tests/integration/postgres.rs
Closes: https://github.com/stacks-sbtc/sbtc/issues/1196
Avoid calling `get_tx_info` if the transaction is a coinbase one, and log it when extracting sbtc txs (deposit ones are already logged with something like `WARN block-observer:load_latest_deposit_requests:load_requests: signer::block_observer: could not validate deposit request error=transaction is coinbase, txid: ..., block hash Some(...)`).
Also removed some random trailing spaces in the first commit.
Added a test for coinbase donation and deposit.
=> fix: ignore (and log) coinbase tx

emily/handler/src/api/handlers/internal.rs, emily/handler/src/common/error.rs, emily/handler/src/context.rs, emily/handler/src/database/accessors.rs, emily/handler/src/database/entries/deposit.rs, emily/handler/src/database/entries/mod.rs, emily/handler/src/database/entries/withdrawal.rs
There were a few small issues that were bothersome around our logs that this PR fixes.
* Remove unused error variants.
* Remove the `Debug` error variant and the associated 418 status code that was associated with those error. The response code is now likely to be 500 now.
* Create more targeted error variants for the errors that can happen.
* Update the logging message and comments around the new error variants.
* Make sure production code is compiled without the `testing` feature.
* Add more logging around errors, upgrade their level.
This is all logging and error refactoring, so no new tests.
=> chore: clean-up logging in Emily v1

signer/src/block_observer.rs, signer/src/config/error.rs, signer/src/config/mod.rs, signer/src/main.rs, signer/src/stacks/wallet.rs, signer/tests/integration/block_observer.rs
This PR makes mandatory for `bootstrap_signer_set` to contain public key of this signer.
Closes: no issue.
Currently, `SignerConfig` have both method `bootstrap_signing_set()` and similarly named field `bootstrap_signing_set`. They also have different types, `BTreeSet<Pubkey>` vs `Vec<Pubkey>`. This can give an impression, that the method just converts `Vec` to `BTreeSet`. But it is wrong, and method also adds one more pubkey to set, which is counterintuitive imo.
I did some lookup through the code, found zero places relying on `bootstrap_signing_set` does not contain pubkey of current signer, so I made `bootstrap_signing_set` always containing the pubkey of current signer, via settings validation.
- Now `bootstrap_signing_set()` always contain same pubkeys as `bootstrap_signing_set` and …
=> chore: make bootstrap_signer_set containing self pubkey mandatory

signer/src/transaction_coordinator.rs, signer/tests/integration/transaction_coordinator.rs
Closes https://github.com/stacks-sbtc/sbtc/issues/1593
This PR updates so that when DKG coordination fails in the transaction coordinator, instead of failing the entire process (aka entirely halt), we now gracefully fall back to using the existing aggregate key if one is available. This improves system resilience by allowing operations to continue even when DKG coordination encounters issues.
Modified `process_new_blocks` to handle DKG coordination failures by falling back to existing aggregate key. The system will now:
1. Attempt DKG coordination as normal
2. On failure, log the error and attempt to use existing aggregate key
3. Only fail if _**no**_ existing aggregate key is available
There is a single test added that verifies fallback behavior works as expected.
=> feat: coordinator processes requests on DKG failure

signer/src/testing/transaction_coordinator.rs, signer/tests/integration/postgres.rs
Address https://github.com/stacks-sbtc/sbtc/issues/1590
We still have cases where the generated data does not have "valid" withdrawals in `should_process_withdrawals` (eg for seed `7437941319183672874`). In ~100 runs of the test, I only got such seed once, so I'm proposing to just drop the non-empty check. Not the best, since we may change stuff and end up with always having zero withdrawals in that test, but that will be probably catch in other places.
Tested with a previously broken seed.
=> chore: use get_rng in should_process_withdrawals

signer/tests/integration/postgres.rs, signer/tests/integration/transaction_signer.rs
Closes: nothing
While investigating something unrelated I noticed we still had some dbs lingering around, this PR adds the missing `drop_db`.
Tests are green, at the end of tests run we no longer have any db (other than `postgres`).
=> chore: add missing `drop_db` in tests

signer/src/bitcoin/packaging.rs
Sorting items by amount of votes gives ability for malicious signer to delay or speedup some requests, thus it should be deleted
Closes: #1661
- don't sort items in packaging anymore (however, we probably want to add sort by some other key in the future)
No new tests needed
=> chore: don't sort items in packaging

signer/src/storage/model.rs, signer/src/storage/sqlx.rs, signer/src/testing/dummy.rs, signer/tests/integration/postgres.rs
Adds a new `Timestamp` model which can be seamlessly used in `sqlx` queries against `TIMESTAMPZ` columns.
- New `Timestamp` type and related `sqlx` implementations.
- `Dummy` implementation which generates timestamps valid for PostgreSQL
- Integration test to verify it works
=> feat: add timestamp support for sqlx+postgres integration

docker/mainnet/README.md, docker/mainnet/docker-compose.yml, docker/mainnet/gh-attestation/entrypoint.sh, docker/mainnet/nodes/docker-compose.chains.yml
Update docker compose to the last docker version
- Update Signer and Blocklist version
- Update Entry Point with GHCR
- Update Stacks Node
- Add links to find the last images release
=> fix: Update docker compose to the last version

docker/observability/vector.toml, signer/src/metrics.rs, signer/src/network/libp2p/bootstrap.rs
This is a PR that adds P2P/networking metrics to Grafana. Currently in drafts, this PR has only one metric (total peers connected) so please feel free to suggest more relevant metrics to add.
Closes: #1131 
Adds a new metric enum to Metrics.rs & updates the 'peer_connected' & 'peer_disconnected' functions to fire the new 'Peers Connected Total' metric.
N/a
=> P2P Metric

signer/src/keys.rs, signer/src/storage/postgres/read.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/transaction_coordinator.rs
Closes https://github.com/stacks-sbtc/sbtc/issues/1739
* After the coordinator submits a rotate-keys contract call, they now bail.
* Sort by `created_at` on ties for the query behind the `get_last_key_rotation` function. Hopefully, this change becomes obsolete after https://github.com/stacks-sbtc/sbtc/pull/1734.
* Fix up the debug implementation for the `PublicKey`. I don't mind removing this and using the implementation in https://github.com/stacks-sbtc/sbtc/pull/1726 to make the merge there better.
I added an integration test. It might be flaky right now, so maybe we need to ignore it for the time being.
=> feat: skip coordinator tenure after a key rotation

.github/workflows/image-build-and-draft-release.yaml
Fix the Git Commit Reference using the Tag Name
Set the GIT_COMMIT to _github.event.client_payload.tag_name_
=> fix: Fix the Git Commit Reference during image building

Makefile
I widely use `cargo clippy --fix`, it can easily eliminate all unused imports or other machine-applicable clippy lints. However, I don't remember sometimes whole long command we use for clippy in CI, which makes me open our Makefile, copy command from it, edit adding --fix flag, which is annoying. This PR aims to solve the problem.
Closes: no issue
Added two new Makefile commands:
`make fix` -- runs `cargo fmt` and `clippy --fix` for all targets we need. If you have any uncommited changes it will bail and only `cargo fmt` will be runned.
`make fix-uncommited` -- same as above, but this command won't bail if you have any uncommited changes and will perform it's work.
I'm not sure if we need both versions of the command since I usually don't afraid to run clippy on uncommited changes if …
=> chore: introduce make fix command

signer/src/metrics.rs, signer/src/proto/convert.rs, signer/src/stacks/api.rs, signer/src/stacks/contracts.rs, signer/tests/devenv/devenv.rs
* Adds metrics around requests to the stacks node that call read-only functions, read data variables, and read map entries.
* Changed the function signatures to take ownership of the string types, since it should be slightly more efficient.
~~I still need to check that this works on devenv.~~ Ran this branch on devenv and everything looked fine. The only thing that is not tested is the new `Metrics::record_data_var`, because we no longer read data variables after https://github.com/stacks-sbtc/sbtc/pull/1734. Also, we can probably remove that function, as well as remove `get_current_signers_aggregate_key`. Let's do that another day.
=> feat: add metrics for smart contract read requests

signer/src/api/info.rs, signer/src/block_observer.rs, signer/src/context/signer_state.rs, signer/src/error.rs, signer/src/request_decider.rs, signer/src/storage/mod.rs, signer/src/storage/postgres/read.rs, signer/src/testing/request_decider.rs, signer/src/transaction_coordinator.rs, signer/src/transaction_signer.rs, signer/tests/integration/request_decider.rs, signer/tests/integration/transaction_coordinator.rs
Closes https://github.com/stacks-sbtc/sbtc/issues/1770
* Change the state object for the bitcoin chain tip to be an `Option<BitcoinBlockRef>` instead of a `BitcoinBlockRef`.
* Make it so that the `get_bitcoin_canonical_chain_tip_ref` and `get_bitcoin_canonical_chain_tip` queries only compile during our tests.
* Use the `SignerState` object for getting the bitcoin chain tip.
I will spin up devenv and check that everything works as expected.
=> fix: do not fetch bitcoin chain tip from db

signer/src/block_observer.rs, signer/src/testing/block_observer.rs, signer/src/transaction_coordinator.rs, signer/tests/integration/block_observer.rs
Closes https://github.com/stacks-sbtc/sbtc/issues/1811
* Move the check for smart contract deployment to the block observer. It's more natural here, and doesn't result in a noisy start when starting the application.
* Updated the tests affected by the change.
I repurposed one of our existing tests to test some of the new functionality. This is the new `get_signer_set_info_checks_for_contract_deployment` test. ~~I'm going to test this on devenv, just waiting for the build at the moment~~ I ran this on devenv and things seemed mostly fine. I saw some "concurrent WSTS activity observed" logs early on and also saw that my first deposit took two bitcoin block to be swept instead of one. The later deposits were promptly swept and those logs didn't show up after a while. I think this is an …
=> feat: move coordinator checks for smart contract deployment to block observer

.github/actions/dockerfiles/Dockerfile.blocklist-client.debian, .github/actions/dockerfiles/Dockerfile.signer.debian, README.md, docker/sbtc/Dockerfile, rust-toolchain.toml, supply-chain/imports.lock
Bumps Rust to 1.90.0 and updates the usual code/docs references.
There were no new clippy warnings generated for this bump.
=> chore: bump rust to 1.90
