stacks-sbtc/sbtc

signer/src/blocklist_client.rs
signer/src/codec.rs
signer/src/config.rs
signer/src/ecdsa.rs
signer/src/error.rs
signer/src/fees.rs
signer/src/lib.rs
signer/src/message.rs
signer/src/network.rs
signer/src/network/grpc_relay.rs
signer/src/network/in_memory.rs
signer/src/packaging.rs
signer/src/utxo.rs

chore: Add #![deny(missing_docs)] to signer

---

.generated-sources/blocklist-openapi-gen/blocklist-client-openapi.json
blocklist-client/src/api/handlers.rs
blocklist-client/src/api/mod.rs
blocklist-client/src/api/routes.rs
blocklist-client/src/client/mod.rs
blocklist-client/src/client/risk_client.rs
blocklist-client/src/common/error.rs
blocklist-client/src/common/mod.rs
blocklist-client/src/config.rs
blocklist-client/src/lib.rs
common/src/lib.rs
common/src/logging.rs
emily/lambda/src/common.rs
emily/lambda/src/errors.rs
emily/lambda/src/eventhandler.rs
emily/lambda/src/lib.rs
emily/lambda/src/operations/chainstate.rs
emily/lambda/src/operations/deposits.rs
emily/lambda/src/operations/withdrawals.rs

Closes #178 
This PR adds deny missing docs to common, blocklist_client and emily crates.

Add deny missing docs in remaining crates

---

Cargo.lock
Cargo.toml
signer/Cargo.toml
signer/src/message.rs
signer/src/message/testing.rs

Closes #173 
This PR adds fields for the `StacksTransactionSignRequest` and `StacksTransactionSignature` message variants, along with tests to ensure that these are signable and encodable.

feat: StacksTransactionSignRequest and StacksTransactionSignature payloads defined

---

signer/src/lib.rs
signer/src/transaction_coordinator.rs
signer/src/transaction_signer.rs

docs: Document design for the transaction coordinator event loop

---

signer/src/error.rs
signer/src/transaction_signer.rs

feat: Transaction signer persisting received decisions

---

contracts/tests/sbtc-withdrawal.test.ts

fix: remove unnecessary inputs in clarity tests

---

.sqlx/query-401d4ec8deeda7e5e51c95c745d79cfd676c534cc3e557fb00cb75ddae4bbc8f.json
.sqlx/query-4b93393697ce37823614bbbbfd84e76dcdd355c9a47484bb4e9f71afa72e0013.json
.sqlx/query-f576df5d7f16771de8432ad64d384b5d429bdcc3463f588895676e6d6c424704.json
signer/src/storage/postgres.rs
signer/tests/integration/transaction_signer.rs

feat: Transaction signer able to participate in WSTS using postgres

---

signer/src/bitcoin.rs
signer/src/block_observer.rs
signer/src/error.rs
signer/src/lib.rs
signer/src/transaction_coordinator.rs
signer/src/transaction_signer.rs
signer/src/wsts_state_machine.rs

closes #235 
This PR adds initial boilerplate and does some refactors to pave the way for implementing a functioning transaction coordinator as designed in #44.

feat: Skeleton implementation of transaction coordinator

---

Cargo.lock
emily/handler/Cargo.toml
emily/handler/src/logging.rs
emily/handler/src/main.rs

resolves: #357
The Emily API needs to be able to compile for an AWS Lambda, but one of the dependencies , `sha2-asm`, can't compile for the aws arm lambda. The API will likely need access to the common library in the future in order to use the transaction library, but for now this ticket removes the common dependency.
The following is the dependency tree when `sbtc` is a dependency of the API:
```
sha2-asm v0.6.4
└── sha2 v0.10.8
├── aws-sigv4 v1.2.2
│   └── aws-runtime v1.3.0
│       ├── aws-config v1.5.3
│       │   └── emily-handler v0.1.0 (/Users/ashtonstephens/workplace/sbtc/emily/handler)
│       ├── aws-sdk-dynamodb v1.36.0
│       │   ├── emily-handler v0.1.0 (/Users/ashtonstephens/workplace/sbtc/emily/handler)
│       │   └── serde_dynamo v4.2.14
│       │       └── emily-handler …
```

tech-debt: Remove common lib from emily handler dependencies.

---

.github/PULL_REQUEST_TEMPLATE.md

Adds a simple pull request template in place of the old one. Originally PRs would be autogenerated with the PR template linked below which requires too much detail for a work in progress project. 
https://github.com/stacks-network/.github/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1
This PR creates a pull request template similar to the pull request descriptions used in practice by @djordon.
Adds a `PULL_REQUEST_TEMPLATE.md` to the `.github` directory.
None.

feat: Simple pull request template.

---

.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/tech-debt.md

Closes: #376 
Adds two new issue templates:
- Chore
- Tech Debt
N/A

documentation: Add two new issue templates.

---

.github/ISSUE_TEMPLATE/tech-debt.md
.github/workflows/unit-tests.yaml

Closes: #N/A
- Prevents the CI workflow for rust unit tests from running twice for every pr.
- Removes a small annoying bit from the tech-debt issue template

feat: Remove extra workflow and make tech-debt ticket less detailed.

---

emily/handler/src/api/handlers/chainstate.rs
emily/handler/src/api/handlers/deposit.rs
emily/handler/src/api/handlers/withdrawal.rs
emily/handler/src/database/accessors.rs
emily/handler/src/database/entries/chainstate.rs
emily/handler/src/database/entries/deposit.rs
emily/handler/src/database/entries/mod.rs
emily/handler/src/database/entries/withdrawal.rs

Closes: Partially #348
This PR ultimately does a refactor that I started because it seemed necessary for the update command, but ended up not being the best use of time. I've decided to open this PR anyway because some of this structure will be useful later down the line when we opt to remove tech debt.
I would consider reviewing this PR loosely.
Uses an Index trait to generalize the DynamoDB behavior across the different table types.
Tested with the integration tests and unit tests.

feat: Generalize Emily DynamoDB Table Accessors

---

.generated-sources/emily/openapi/emily-openapi-spec.json
Makefile
emily/handler/src/api/handlers/deposit.rs
emily/handler/src/api/handlers/withdrawal.rs
emily/handler/src/api/models/withdrawal/requests.rs
emily/handler/src/common/error.rs
emily/handler/src/database/accessors.rs
emily/handler/src/database/entries/chainstate.rs
emily/handler/src/database/entries/deposit.rs
emily/handler/src/database/entries/mod.rs
emily/handler/src/database/entries/withdrawal.rs
emily/handler/tests/integration/accessors.rs
emily/handler/tests/integration/complex/reorg.rs
emily/handler/tests/integration/endpoints/deposit.rs
emily/handler/tests/integration/endpoints/withdrawal.rs
emily/handler/tests/integration/populate/mod.rs

Closes: #N/A
Part of the reorg handling PR, but broken up.
Adds versioned table entries with some generic handling.
Tested with integration tests.

Versioned table entries (reorg part 2/4)

---

signer/src/config.rs

Re-adds support for 33-byte Stacks private keys. 
This is due to the fact that the private key needs to be the same as the one used for stacking so that compensations can be calculated correctly:
> "By securing the sBTC protocol, signers are compensated proportionally to their stacked STX."
This increases the chances that a user will copy-paste a Stacks-generated private key, which contains an extra byte indicating whether or not its public keys should be compressed or not.
Add an extra check to the private key deserializer for length and return an appropriate error if not 64 or 66 characters (hex).

re-add support for 33-byte stacks private keys

---

signer/src/block_observer.rs
signer/src/stacks/events.rs
signer/src/testing/transaction_signer.rs
signer/src/transaction_coordinator.rs
signer/src/transaction_signer.rs

feat: Bitcoin chain tip validation in transaction signer and coordinator

---

emily/handler/tests/integration/deposit.rs
emily/handler/tests/integration/withdrawal.rs

Fixes a typo I introduced in #677

nit: Fix missing word in test comment.

---

emily/handler/tests/integration/deposit.rs
emily/handler/tests/integration/withdrawal.rs

This is just a quick PR which runs `cargo fmt` on `main` which will help clear up some of the diffs in currently open PRs.

chore: cargo fmt

---

.generated-sources/blocklist-api/Cargo.toml
Cargo.lock
contracts/contracts/sbtc-bootstrap-signers.clar
contracts/contracts/sbtc-registry.clar
contracts/tests/sbtc-bootstrap-signers.test.ts
pnpm-lock.yaml

This PR adds a print statement to the 'key-rotation' function as required in #689. 
Closes: #689 
Single print function added.
Successful key-rotation test added to check printed events against inputs. There is a caveat here, however, as we've left out the "newAddress" field in this check. We've left it out because the multi-sig stacks address is created at run-time & random, making it impossible to check against a predetermined value.

Clarity/Key Rotation Print

---

signer/src/config/mod.rs
signer/src/main.rs

As requested [here](https://github.com/stacks-network/sbtc/pull/714#discussion_r1819362327).

fix: linter failing after #714

---

signer/tests/integration/emily.rs

Fix broken test after merge.
Also renames it since it's not really an e2e test.

fix: fix broken test

---

docker/sbtc/signer/signer-config.toml
docker/stacks/stacks-regtest-miner.toml
signer/src/bitcoin/rpc.rs
signer/src/error.rs
signer/src/transaction_coordinator.rs

* Update the configs with the values that are needed for the demo
* Some minor logging updates
No tests, these changes are logging related, or updating the config in the dev environment.

chore: minor demo updates

---

Makefile
docker/sbtc/signer/signer-config.toml
signer/build.rs

Fixes some issues we were seeing in the devenv
* Don't compile protobufs automatically. We don't use them right now so this will have no effect. We can revisit this later when switch to using them.
* Add in a missing config field.
* Added a new makefile command. Perhaps this should just be an argument or something
No tests, but this is config/build changes and even then it does not touch any production code.

chore: more devnet setup changes

---

signer/src/stacks/contracts.rs

This is basically due to an endian issue with our bitcoin block hash type. This fixes the endianness of what is sent in the clarity contract call.
* Change the endianness of the bitcoin block hash sent in the clarity contract calls.
We don't run stacks-core integration tests in CI, so we need to run these tests in devenv, which is running now.

fix: byte reverse bug in contract call

---

docker/bridge-website/Dockerfile

Update remote url for docker image update on the sbtc bridge docker file

chore - update bridge git remote for docker

---

signer/tests/integration/rotate_keys.rs

fix: 801 merge test fail

---

.github/actions/dockerfiles/Dockerfile.blocklist-client.debian
.github/actions/dockerfiles/Dockerfile.signer.debian

Closes: #843
Fixes name issue
Makes the binaries debug

fix: incompatible target name and use debug release

---

README.md

Add devenv demo steps
Add in the readme the steps used for devenv demo.

chore: add devenv demo steps

---

.github/workflows/image-build.yaml

Closes: #N/A
Add the possibility to generate the docker image from any branch manually and every night at 2 AM from the main
Add workflow dispatch and cron trigger

feat: Add manual action for building docker images from every branch and on cron from the main

---

signer/src/main.rs
signer/src/transaction_signer.rs

update logging so we know what wsts messages came from where

---

signer/src/proto/convert.rs
signer/src/stacks/contracts.rs
signer/src/testing/dummy.rs

Closes: https://github.com/stacks-network/sbtc/issues/891
Adds missing proto conversions tests.

tests: add missing proto conversion tests

---

signer/src/blocklist_client.rs

Avoid double slashes in api calls.
Tested locally with
```
[blocklist_client]
endpoint = "http://blocklist-client:3030"
```
and adding the API key.

fix: remove trailing slash from blocklist client

---

Cargo.lock
docker/prodlike/config/signer-config.toml
docker/sbtc/signer/signer-config.toml
signer/Cargo.toml
signer/src/config/default.toml
signer/src/config/error.rs
signer/src/config/mod.rs
signer/src/main.rs

Closes: #1013
Added requested parameters to signer config, switched from hardcoded parameters to using config while creating coordinator in `main.rs`
Added 3 new tests in `signer/src/config/mod.rs::tests` and modified `signer/src/config/mod.rs::tests::default_config_toml_loads`

[Feature]: Expose tx-coordinator fields as configurable parameters

---

README.md

Fix README links/docs

---

emily/cdk/lib/emily-stack.ts

Closes: #?
Adds on demand provisioning to Emily ddb tables.

On demand ddb tables

---

docker/prodlike/config/signer-config.toml
docker/sbtc/signer/signer-config.toml
emily/cdk/lib/emily-stack.ts
signer/src/config/default.toml
signer/src/main.rs

remove redundant words in comment

chore: remove redundant words in comment

---

signer/src/config/default.toml
signer/src/config/mod.rs

Temp bump until https://github.com/stacks-network/sbtc/pull/1048 is merged.

chore: bump context window to 1000

---

.github/actions/dockerfiles/Dockerfile.blocklist-client.debian
.github/actions/dockerfiles/Dockerfile.signer.debian

Adds `c++` compiler for zmq.
Successful build run: https://github.com/stacks-network/sbtc/actions/runs/12234770996/job/34124649958

fix: add c++ compiler

---

signer/src/request_decider.rs

Addresses https://github.com/stacks-network/sbtc/issues/1046.
* Reject deposits if any of the inputs cannot be accepted.
This is the analog of https://github.com/stacks-network/sbtc/pull/1045.

fix: only accpt deposits if all are fine

---

sbtc/src/deposits.rs

Closes https://github.com/stacks-network/sbtc/issues/1078.
* Include 16 in the check for small, minimal pushes.

fix: handle locktime of 16 correctly

---

emily/README.md

Closes: #1053
Adds Emily API doc.

Emily docs

---

docker/bitcoin/bitcoin.conf
docker/testnet/bitcoin/bitcoin.conf

Closes: #?
It seems we don't actually need `coinstatsindex`.
Tests are green, devenv demo run okay.

fix: remove `coinstatsindex`

---

.github/actions/dockerfiles/Dockerfile.blocklist-client.debian
.github/actions/dockerfiles/Dockerfile.signer.debian

Bug from `069867d7404635d7556f881609eb171374c7be20`
Test build in https://github.com/stacks-network/sbtc/actions/runs/12354218433

Fix binary path for `release` Docker builds

---

Cargo.lock
signer/Cargo.toml

Update the version of WSTS.
* Upgrade the revision of WSTS
This is a non-breaking update of a dependency so if the tests pass then we are okay.

chore: bump wsts version

---

signer/src/api/new_block.rs
signer/tests/fixtures/rotate-keys-and-invalid-event.json

Closes: https://github.com/stacks-network/sbtc/issues/1182
Instead of returning after the first invalid event (skipping the rest of the events), we continue.
Add a test for this.

fix: continue processing events in new block after unknown events

---

.github/workflows/buf-ci.yaml
.github/workflows/contract-tests.yaml
.github/workflows/image-build.yaml
.github/workflows/unit-tests.yaml

Pin action by hash in CI workflows
Closes: https://github.com/stacks-network/sbtc/issues/1235
- Add hash to every CI action

feat: Pin action by hash in CI workflows

---

emily/handler/src/api/handlers/chainstate.rs
emily/handler/src/api/handlers/deposit.rs
emily/handler/src/api/handlers/health.rs
emily/handler/src/api/handlers/limits.rs
emily/handler/src/api/handlers/testing.rs
emily/handler/src/api/handlers/withdrawal.rs

Remove outdated TODOs in emily.
Remove TODOs that were already addressed:
- https://github.com/stacks-network/sbtc/issues/271
- https://github.com/stacks-network/sbtc/issues/396
Comment only changes.

chore: remove outdated todos

---

.generated-sources/emily/client/rust/private/src/models/deposit_update.rs
.generated-sources/emily/client/rust/private/src/models/withdrawal_update.rs
.generated-sources/emily/client/rust/public/src/models/deposit_update.rs
.generated-sources/emily/client/rust/public/src/models/withdrawal_update.rs
.generated-sources/emily/client/rust/testing/src/models/deposit_update.rs
.generated-sources/emily/client/rust/testing/src/models/withdrawal_update.rs
emily/cdk/lib/emily-stack-utils.ts
emily/cdk/lib/emily-stack.ts
emily/handler/src/api/handlers/internal.rs
emily/handler/src/api/models/common/mod.rs
emily/handler/src/api/models/deposit/requests.rs
emily/handler/src/api/models/withdrawal/requests.rs
emily/handler/src/api/routes/mod.rs
emily/handler/src/common/error.rs
emily/handler/src/database/accessors.rs
emily/handler/src/database/entries/chainstate.rs
emily/handler/src/database/entries/deposit.rs
emily/handler/src/database/entries/mod.rs
emily/handler/src/database/entries/withdrawal.rs
emily/openapi-gen/generated-specs/private-emily-openapi-spec.json
emily/openapi-gen/generated-specs/public-emily-openapi-spec.json
emily/openapi-gen/generated-specs/testing-emily-openapi-spec.json

Address some typos and a stale comment (after https://github.com/stacks-network/sbtc/pull/1112)
Refactor only.

chore: fix some typos

---

README.md

Closes: #?
Remove discord unused discord badge.

chore: remove discord badge

---

.generated-sources/emily/client/rust/private/src/apis/deposit_api.rs
.generated-sources/emily/client/rust/public/src/apis/deposit_api.rs
.generated-sources/emily/client/rust/testing/src/apis/deposit_api.rs
emily/handler/src/api/handlers/deposit.rs
emily/handler/tests/integration/deposit.rs
emily/openapi-gen/generated-specs/private-emily-openapi-spec.json
emily/openapi-gen/generated-specs/public-emily-openapi-spec.json
emily/openapi-gen/generated-specs/testing-emily-openapi-spec.json

Closes: #518 
- return 200 if a copy of the deposit already exists.
- added an integration test

[chore] duplicate check on create_deposit

---

scripts/emily-dev/.env

This PR just adds the example parameter for the Emily deployment
- Add Deployer Address Example

feat: Add example deployer address

---

signer/src/storage/in_memory.rs
signer/src/storage/mod.rs
signer/src/storage/postgres.rs
signer/tests/integration/postgres.rs

Closes https://github.com/stacks-network/sbtc/issues/1499
* Add a query that computes the total withdrawn amounts.
This PR adds two integration tests for the query.

feat: add query that computes aggregate withdrawn amounts

---

scripts/deploy-emily.sh

Improve deployment changes visibility adding CDK Diff
- Add cdk diff
- Add confirmation step

feat: Improve deployment changes visibility adding CDK Diff

---

Cargo.lock
Cargo.toml
supply-chain/audits.toml
supply-chain/config.toml

Bump WSTS to HEAD of main branch

chore: bump WSTS

---

signer/src/bitcoin/fees.rs
signer/src/network/libp2p/network.rs
signer/src/stacks/api.rs
signer/src/stacks/wallet.rs

As the title says; just fixes a few spelling mistakes in comments I came across during review.

chore: fix a few spelling mistakes in comments

---

docker/docker-compose.yml

Bump devenv stacks-api to make it work with latest leather version.
Tried deposit and withdrawal via bridge, it worked*.
\* there was an issue with fetching the withdrawal details in the bridge, but it's not related to this or the api probably; I will investigate that separately.

fix: update devenv stacks-api

---

signers.sh

QoL improvement for `signers.sh`
- Adds a `help` command (and now prints help for invalid commands)
- Adds a `fund-btc <addr> <sats>` command which just forwards to demo-cli (to avoid users needing to use cargo commands).
```
Usage: ./signers.sh <command> [arguments]
Available commands:
run <number>              Run the specified number of signers (e.g., ./signers.sh run 3)
demo                      Execute predefined demo operations (donation, deposit)
fund-btc <addr> <sats>    Fund a Bitcoin address from the regtest wallet (e.g., ./signers.sh fund-btc <address> 100000)
info                      Get signer info from the database
stop                      Stop all running signer processes
help                      Display this help message
```

[feat] add fund-btc command to signers.sh

---

Cargo.toml

Closes: no issue
removing unused dependency from `Cargo.toml`
no new tests needed

chore: remove openssl

---

Makefile
docker/docker-compose.test.yml
docker/sbtc/Dockerfile
emily/handler/Cargo.toml
emily/handler/src/bin/emily-server.rs
emily/handler/src/context.rs
emily/openapi-gen/Cargo.toml

Closes https://github.com/stacks-sbtc/sbtc/issues/395
1. Make sure that the functions that wipe the database are not compiled by default for Emily
This is just a build change.

build: do not build emily with testing feature

---

signer/src/metrics.rs
signer/src/transaction_signer.rs

This is part of https://github.com/stacks-sbtc/sbtc/issues/1490
* Move some of the metrics to a more central location
This is just a refactor that moves metrics logic around. We don't really test logging and stuff like that yet.

refactor: centralize more metric logic

---

Cargo.lock
Cargo.toml
protobufs/crypto/wsts/wsts.proto
signer/Cargo.toml
signer/src/dkg/verification.rs
signer/src/proto/convert.rs
signer/src/proto/generated/crypto.wsts.rs
signer/src/testing/dummy.rs
signer/src/testing/wsts.rs
signer/src/transaction_coordinator.rs
signer/src/wsts_state_machine.rs
signer/tests/integration/transaction_coordinator.rs
supply-chain/audits.toml

Update the `WSTS` dependency
Closes: #1778 
This PR updates the `WSTS` dependency to include numerous security audit fixes and feature additions.  
No new functionality has been added to `sBTC`, so as long as existing tests pass the new dependency should be working.

chore: update wsts dependency

---

Cargo.lock
Cargo.toml
protobufs/crypto/wsts/wsts.proto
signer/Cargo.toml
signer/src/dkg/verification.rs
signer/src/proto/convert.rs
signer/src/proto/generated/crypto.wsts.rs
signer/src/testing/dummy.rs
signer/src/testing/wsts.rs
signer/src/transaction_coordinator.rs
signer/src/wsts_state_machine.rs
signer/tests/integration/transaction_coordinator.rs
supply-chain/audits.toml

Reverts stacks-sbtc/sbtc#1789
* Undo the WSTS update so that the next sbtc release is less of a breaking change.

Revert "chore: update wsts dependency"
